// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/authentication.dart';
import 'api/bootstrap.dart';
import 'api/library.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiBootstrapInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1403149634;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutterustmusic',
        ioDirectory: '../../bridges/flutter/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiLibraryQqMusicOwnedPlaylistLoadHandleCancel({
    required QqMusicOwnedPlaylistLoadHandle that,
  });

  bool crateApiLibraryQqMusicOwnedPlaylistLoadHandleIsActive({
    required QqMusicOwnedPlaylistLoadHandle that,
  });

  Future<QqMusicOwnedPlaylistLoad>
  crateApiLibraryQqMusicOwnedPlaylistLoadHandleRun({
    required QqMusicOwnedPlaylistLoadHandle that,
  });

  Future<QqMusicQrLoginUpdate>
  crateApiAuthenticationQqMusicQrLoginSessionHandleAdvance({
    required QqMusicQrLoginSessionHandle that,
  });

  bool crateApiAuthenticationQqMusicQrLoginSessionHandleCancel({
    required QqMusicQrLoginSessionHandle that,
  });

  bool crateApiAuthenticationQqMusicQrLoginSessionHandleIsActive({
    required QqMusicQrLoginSessionHandle that,
  });

  QqMusicOwnedPlaylistLoadHandle crateApiLibraryBeginQqMusicOwnedPlaylistLoad();

  BootstrapStatus crateApiBootstrapBootstrapStatus();

  bool crateApiAuthenticationCancelQqMusicCredentialVerification({
    required int attemptId,
  });

  bool crateApiAuthenticationCancelQqMusicWechatQrLoginStart({
    required int attemptId,
  });

  QqMusicCredentialExport
  crateApiAuthenticationExportQqMusicCredentialForSecureStorage();

  Future<void> crateApiBootstrapInitApp();

  bool crateApiAuthenticationQqMusicHasAuthenticatedCredential();

  int? crateApiAuthenticationReserveQqMusicCredentialVerification();

  int crateApiAuthenticationReserveQqMusicWechatQrLoginStart();

  QqMusicCredentialRestore
  crateApiAuthenticationRestoreQqMusicCredentialFromSecureStorage({
    Uint8List? secretBytes,
  });

  Future<QqMusicQrLoginStart> crateApiAuthenticationStartQqMusicWechatQrLogin({
    required int attemptId,
  });

  Future<QqMusicCredentialVerification>
  crateApiAuthenticationVerifyRestoredQqMusicCredential({
    required int attemptId,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QqMusicOwnedPlaylistLoadHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QqMusicOwnedPlaylistLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicOwnedPlaylistLoadHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QqMusicQrLoginSessionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiLibraryQqMusicOwnedPlaylistLoadHandleCancel({
    required QqMusicOwnedPlaylistLoadHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleCancelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleCancelConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicOwnedPlaylistLoadHandle_cancel",
        argNames: ["that"],
      );

  @override
  bool crateApiLibraryQqMusicOwnedPlaylistLoadHandleIsActive({
    required QqMusicOwnedPlaylistLoadHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleIsActiveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleIsActiveConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicOwnedPlaylistLoadHandle_is_active",
        argNames: ["that"],
      );

  @override
  Future<QqMusicOwnedPlaylistLoad>
  crateApiLibraryQqMusicOwnedPlaylistLoadHandleRun({
    required QqMusicOwnedPlaylistLoadHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_owned_playlist_load,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleRunConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiLibraryQqMusicOwnedPlaylistLoadHandleRunConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicOwnedPlaylistLoadHandle_run",
        argNames: ["that"],
      );

  @override
  Future<QqMusicQrLoginUpdate>
  crateApiAuthenticationQqMusicQrLoginSessionHandleAdvance({
    required QqMusicQrLoginSessionHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_qr_login_update,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationQqMusicQrLoginSessionHandleAdvanceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationQqMusicQrLoginSessionHandleAdvanceConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicQrLoginSessionHandle_advance",
        argNames: ["that"],
      );

  @override
  bool crateApiAuthenticationQqMusicQrLoginSessionHandleCancel({
    required QqMusicQrLoginSessionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationQqMusicQrLoginSessionHandleCancelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationQqMusicQrLoginSessionHandleCancelConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicQrLoginSessionHandle_cancel",
        argNames: ["that"],
      );

  @override
  bool crateApiAuthenticationQqMusicQrLoginSessionHandleIsActive({
    required QqMusicQrLoginSessionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationQqMusicQrLoginSessionHandleIsActiveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationQqMusicQrLoginSessionHandleIsActiveConstMeta =>
      const TaskConstMeta(
        debugName: "QqMusicQrLoginSessionHandle_is_active",
        argNames: ["that"],
      );

  @override
  QqMusicOwnedPlaylistLoadHandle
  crateApiLibraryBeginQqMusicOwnedPlaylistLoad() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryBeginQqMusicOwnedPlaylistLoadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryBeginQqMusicOwnedPlaylistLoadConstMeta =>
      const TaskConstMeta(
        debugName: "begin_qq_music_owned_playlist_load",
        argNames: [],
      );

  @override
  BootstrapStatus crateApiBootstrapBootstrapStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bootstrap_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBootstrapBootstrapStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBootstrapBootstrapStatusConstMeta =>
      const TaskConstMeta(debugName: "bootstrap_status", argNames: []);

  @override
  bool crateApiAuthenticationCancelQqMusicCredentialVerification({
    required int attemptId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(attemptId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationCancelQqMusicCredentialVerificationConstMeta,
        argValues: [attemptId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationCancelQqMusicCredentialVerificationConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_qq_music_credential_verification",
        argNames: ["attemptId"],
      );

  @override
  bool crateApiAuthenticationCancelQqMusicWechatQrLoginStart({
    required int attemptId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(attemptId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationCancelQqMusicWechatQrLoginStartConstMeta,
        argValues: [attemptId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationCancelQqMusicWechatQrLoginStartConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_qq_music_wechat_qr_login_start",
        argNames: ["attemptId"],
      );

  @override
  QqMusicCredentialExport
  crateApiAuthenticationExportQqMusicCredentialForSecureStorage() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_credential_export,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationExportQqMusicCredentialForSecureStorageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationExportQqMusicCredentialForSecureStorageConstMeta =>
      const TaskConstMeta(
        debugName: "export_qq_music_credential_for_secure_storage",
        argNames: [],
      );

  @override
  Future<void> crateApiBootstrapInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBootstrapInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBootstrapInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiAuthenticationQqMusicHasAuthenticatedCredential() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationQqMusicHasAuthenticatedCredentialConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationQqMusicHasAuthenticatedCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "qq_music_has_authenticated_credential",
        argNames: [],
      );

  @override
  int? crateApiAuthenticationReserveQqMusicCredentialVerification() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationReserveQqMusicCredentialVerificationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationReserveQqMusicCredentialVerificationConstMeta =>
      const TaskConstMeta(
        debugName: "reserve_qq_music_credential_verification",
        argNames: [],
      );

  @override
  int crateApiAuthenticationReserveQqMusicWechatQrLoginStart() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationReserveQqMusicWechatQrLoginStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationReserveQqMusicWechatQrLoginStartConstMeta =>
      const TaskConstMeta(
        debugName: "reserve_qq_music_wechat_qr_login_start",
        argNames: [],
      );

  @override
  QqMusicCredentialRestore
  crateApiAuthenticationRestoreQqMusicCredentialFromSecureStorage({
    Uint8List? secretBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_list_prim_u_8_strict(secretBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_credential_restore,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationRestoreQqMusicCredentialFromSecureStorageConstMeta,
        argValues: [secretBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationRestoreQqMusicCredentialFromSecureStorageConstMeta =>
      const TaskConstMeta(
        debugName: "restore_qq_music_credential_from_secure_storage",
        argNames: ["secretBytes"],
      );

  @override
  Future<QqMusicQrLoginStart> crateApiAuthenticationStartQqMusicWechatQrLogin({
    required int attemptId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(attemptId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_qr_login_start,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthenticationStartQqMusicWechatQrLoginConstMeta,
        argValues: [attemptId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthenticationStartQqMusicWechatQrLoginConstMeta =>
      const TaskConstMeta(
        debugName: "start_qq_music_wechat_qr_login",
        argNames: ["attemptId"],
      );

  @override
  Future<QqMusicCredentialVerification>
  crateApiAuthenticationVerifyRestoredQqMusicCredential({
    required int attemptId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(attemptId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qq_music_credential_verification,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiAuthenticationVerifyRestoredQqMusicCredentialConstMeta,
        argValues: [attemptId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiAuthenticationVerifyRestoredQqMusicCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "verify_restored_qq_music_credential",
        argNames: ["attemptId"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QqMusicOwnedPlaylistLoadHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QqMusicOwnedPlaylistLoadHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QqMusicQrLoginSessionHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle;

  @protected
  QqMusicOwnedPlaylistLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BootstrapStatus dco_decode_bootstrap_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BootstrapStatus(
      coreVersion: dco_decode_String(arr[0]),
      provider: dco_decode_provider_status(arr[1]),
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      raw,
    );
  }

  @protected
  QqMusicCredentialExportFailure
  dco_decode_box_autoadd_qq_music_credential_export_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_credential_export_failure(raw);
  }

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_box_autoadd_qq_music_credential_restore_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_credential_restore_failure(raw);
  }

  @protected
  QqMusicCredentialRestoreState
  dco_decode_box_autoadd_qq_music_credential_restore_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_credential_restore_state(raw);
  }

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_box_autoadd_qq_music_credential_verification_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_credential_verification_failure(raw);
  }

  @protected
  QqMusicCredentialVerificationState
  dco_decode_box_autoadd_qq_music_credential_verification_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_credential_verification_state(raw);
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure
  dco_decode_box_autoadd_qq_music_owned_playlist_load_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_owned_playlist_load_failure(raw);
  }

  @protected
  QqMusicQrChallenge dco_decode_box_autoadd_qq_music_qr_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_qr_challenge(raw);
  }

  @protected
  QqMusicQrLoginFailure dco_decode_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_qr_login_failure(raw);
  }

  @protected
  QqMusicQrLoginState dco_decode_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qq_music_qr_login_state(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LibraryPlaylistSummary dco_decode_library_playlist_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LibraryPlaylistSummary(
      providerId: dco_decode_String(arr[0]),
      opaqueId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artworkUri: dco_decode_opt_String(arr[3]),
      trackCount: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LibraryPlaylistSummary> dco_decode_list_library_playlist_summary(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_library_playlist_summary)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  QqMusicQrLoginSessionHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
            raw,
          );
  }

  @protected
  QqMusicCredentialExportFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_export_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_credential_export_failure(raw);
  }

  @protected
  QqMusicCredentialRestoreFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_credential_restore_failure(raw);
  }

  @protected
  QqMusicCredentialRestoreState?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_credential_restore_state(raw);
  }

  @protected
  QqMusicCredentialVerificationFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_credential_verification_failure(raw);
  }

  @protected
  QqMusicCredentialVerificationState?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_state(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_credential_verification_state(raw);
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_owned_playlist_load_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_owned_playlist_load_failure(raw);
  }

  @protected
  QqMusicQrChallenge? dco_decode_opt_box_autoadd_qq_music_qr_challenge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_qr_challenge(raw);
  }

  @protected
  QqMusicQrLoginFailure? dco_decode_opt_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_qr_login_failure(raw);
  }

  @protected
  QqMusicQrLoginState? dco_decode_opt_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_qq_music_qr_login_state(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ProviderStatus dco_decode_provider_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProviderStatus(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      implementedCapabilities: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  QqMusicCredentialExport dco_decode_qq_music_credential_export(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QqMusicCredentialExport(
      secretBytes: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      failure: dco_decode_opt_box_autoadd_qq_music_credential_export_failure(
        arr[1],
      ),
    );
  }

  @protected
  QqMusicCredentialExportFailure dco_decode_qq_music_credential_export_failure(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicCredentialExportFailure.values[raw as int];
  }

  @protected
  QqMusicCredentialRestore dco_decode_qq_music_credential_restore(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QqMusicCredentialRestore(
      state: dco_decode_opt_box_autoadd_qq_music_credential_restore_state(
        arr[0],
      ),
      failure: dco_decode_opt_box_autoadd_qq_music_credential_restore_failure(
        arr[1],
      ),
    );
  }

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_qq_music_credential_restore_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicCredentialRestoreFailure.values[raw as int];
  }

  @protected
  QqMusicCredentialRestoreState dco_decode_qq_music_credential_restore_state(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicCredentialRestoreState.values[raw as int];
  }

  @protected
  QqMusicCredentialVerification dco_decode_qq_music_credential_verification(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QqMusicCredentialVerification(
      state: dco_decode_opt_box_autoadd_qq_music_credential_verification_state(
        arr[0],
      ),
      failure:
          dco_decode_opt_box_autoadd_qq_music_credential_verification_failure(
            arr[1],
          ),
    );
  }

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_qq_music_credential_verification_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicCredentialVerificationFailure.values[raw as int];
  }

  @protected
  QqMusicCredentialVerificationState
  dco_decode_qq_music_credential_verification_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicCredentialVerificationState.values[raw as int];
  }

  @protected
  QqMusicOwnedPlaylistLoad dco_decode_qq_music_owned_playlist_load(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QqMusicOwnedPlaylistLoad(
      playlists: dco_decode_list_library_playlist_summary(arr[0]),
      failure: dco_decode_opt_box_autoadd_qq_music_owned_playlist_load_failure(
        arr[1],
      ),
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure
  dco_decode_qq_music_owned_playlist_load_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadFailure.values[raw as int];
  }

  @protected
  QqMusicQrChallenge dco_decode_qq_music_qr_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QqMusicQrChallenge(
      imageFormat: dco_decode_qq_music_qr_image_format(arr[0]),
      imageBytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  QqMusicQrImageFormat dco_decode_qq_music_qr_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrImageFormat.values[raw as int];
  }

  @protected
  QqMusicQrLoginFailure dco_decode_qq_music_qr_login_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrLoginFailure.values[raw as int];
  }

  @protected
  QqMusicQrLoginStart dco_decode_qq_music_qr_login_start(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QqMusicQrLoginStart(
      session:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
            arr[0],
          ),
      challenge: dco_decode_opt_box_autoadd_qq_music_qr_challenge(arr[1]),
      failure: dco_decode_opt_box_autoadd_qq_music_qr_login_failure(arr[2]),
    );
  }

  @protected
  QqMusicQrLoginState dco_decode_qq_music_qr_login_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QqMusicQrLoginState.values[raw as int];
  }

  @protected
  QqMusicQrLoginUpdate dco_decode_qq_music_qr_login_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QqMusicQrLoginUpdate(
      state: dco_decode_opt_box_autoadd_qq_music_qr_login_state(arr[0]),
      failure: dco_decode_opt_box_autoadd_qq_music_qr_login_failure(arr[1]),
      sessionActive: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  QqMusicOwnedPlaylistLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicOwnedPlaylistLoadHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QqMusicQrLoginSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BootstrapStatus sse_decode_bootstrap_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_coreVersion = sse_decode_String(deserializer);
    var var_provider = sse_decode_provider_status(deserializer);
    return BootstrapStatus(
      coreVersion: var_coreVersion,
      provider: var_provider,
    );
  }

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      deserializer,
    ));
  }

  @protected
  QqMusicCredentialExportFailure
  sse_decode_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_credential_export_failure(deserializer));
  }

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_credential_restore_failure(deserializer));
  }

  @protected
  QqMusicCredentialRestoreState
  sse_decode_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_credential_restore_state(deserializer));
  }

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_credential_verification_failure(deserializer));
  }

  @protected
  QqMusicCredentialVerificationState
  sse_decode_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_credential_verification_state(deserializer));
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure
  sse_decode_box_autoadd_qq_music_owned_playlist_load_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_owned_playlist_load_failure(deserializer));
  }

  @protected
  QqMusicQrChallenge sse_decode_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_qr_challenge(deserializer));
  }

  @protected
  QqMusicQrLoginFailure sse_decode_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_qr_login_failure(deserializer));
  }

  @protected
  QqMusicQrLoginState sse_decode_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qq_music_qr_login_state(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LibraryPlaylistSummary sse_decode_library_playlist_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerId = sse_decode_String(deserializer);
    var var_opaqueId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artworkUri = sse_decode_opt_String(deserializer);
    var var_trackCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    return LibraryPlaylistSummary(
      providerId: var_providerId,
      opaqueId: var_opaqueId,
      title: var_title,
      artworkUri: var_artworkUri,
      trackCount: var_trackCount,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LibraryPlaylistSummary> sse_decode_list_library_playlist_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LibraryPlaylistSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_library_playlist_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QqMusicQrLoginSessionHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicCredentialExportFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_credential_export_failure(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicCredentialRestoreFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_credential_restore_failure(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicCredentialRestoreState?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_credential_restore_state(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicCredentialVerificationFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_credential_verification_failure(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicCredentialVerificationState?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_credential_verification_state(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_owned_playlist_load_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_owned_playlist_load_failure(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  QqMusicQrChallenge? sse_decode_opt_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_qr_challenge(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QqMusicQrLoginFailure? sse_decode_opt_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_qr_login_failure(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QqMusicQrLoginState? sse_decode_opt_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qq_music_qr_login_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderStatus sse_decode_provider_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_implementedCapabilities = sse_decode_list_String(deserializer);
    return ProviderStatus(
      id: var_id,
      displayName: var_displayName,
      implementedCapabilities: var_implementedCapabilities,
    );
  }

  @protected
  QqMusicCredentialExport sse_decode_qq_music_credential_export(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretBytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_failure =
        sse_decode_opt_box_autoadd_qq_music_credential_export_failure(
          deserializer,
        );
    return QqMusicCredentialExport(
      secretBytes: var_secretBytes,
      failure: var_failure,
    );
  }

  @protected
  QqMusicCredentialExportFailure sse_decode_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicCredentialExportFailure.values[inner];
  }

  @protected
  QqMusicCredentialRestore sse_decode_qq_music_credential_restore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state =
        sse_decode_opt_box_autoadd_qq_music_credential_restore_state(
          deserializer,
        );
    var var_failure =
        sse_decode_opt_box_autoadd_qq_music_credential_restore_failure(
          deserializer,
        );
    return QqMusicCredentialRestore(state: var_state, failure: var_failure);
  }

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_qq_music_credential_restore_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicCredentialRestoreFailure.values[inner];
  }

  @protected
  QqMusicCredentialRestoreState sse_decode_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicCredentialRestoreState.values[inner];
  }

  @protected
  QqMusicCredentialVerification sse_decode_qq_music_credential_verification(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state =
        sse_decode_opt_box_autoadd_qq_music_credential_verification_state(
          deserializer,
        );
    var var_failure =
        sse_decode_opt_box_autoadd_qq_music_credential_verification_failure(
          deserializer,
        );
    return QqMusicCredentialVerification(
      state: var_state,
      failure: var_failure,
    );
  }

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicCredentialVerificationFailure.values[inner];
  }

  @protected
  QqMusicCredentialVerificationState
  sse_decode_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicCredentialVerificationState.values[inner];
  }

  @protected
  QqMusicOwnedPlaylistLoad sse_decode_qq_music_owned_playlist_load(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playlists = sse_decode_list_library_playlist_summary(deserializer);
    var var_failure =
        sse_decode_opt_box_autoadd_qq_music_owned_playlist_load_failure(
          deserializer,
        );
    return QqMusicOwnedPlaylistLoad(
      playlists: var_playlists,
      failure: var_failure,
    );
  }

  @protected
  QqMusicOwnedPlaylistLoadFailure
  sse_decode_qq_music_owned_playlist_load_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicOwnedPlaylistLoadFailure.values[inner];
  }

  @protected
  QqMusicQrChallenge sse_decode_qq_music_qr_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_imageFormat = sse_decode_qq_music_qr_image_format(deserializer);
    var var_imageBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return QqMusicQrChallenge(
      imageFormat: var_imageFormat,
      imageBytes: var_imageBytes,
    );
  }

  @protected
  QqMusicQrImageFormat sse_decode_qq_music_qr_image_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicQrImageFormat.values[inner];
  }

  @protected
  QqMusicQrLoginFailure sse_decode_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicQrLoginFailure.values[inner];
  }

  @protected
  QqMusicQrLoginStart sse_decode_qq_music_qr_login_start(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
          deserializer,
        );
    var var_challenge = sse_decode_opt_box_autoadd_qq_music_qr_challenge(
      deserializer,
    );
    var var_failure = sse_decode_opt_box_autoadd_qq_music_qr_login_failure(
      deserializer,
    );
    return QqMusicQrLoginStart(
      session: var_session,
      challenge: var_challenge,
      failure: var_failure,
    );
  }

  @protected
  QqMusicQrLoginState sse_decode_qq_music_qr_login_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QqMusicQrLoginState.values[inner];
  }

  @protected
  QqMusicQrLoginUpdate sse_decode_qq_music_qr_login_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_opt_box_autoadd_qq_music_qr_login_state(
      deserializer,
    );
    var var_failure = sse_decode_opt_box_autoadd_qq_music_qr_login_failure(
      deserializer,
    );
    var var_sessionActive = sse_decode_bool(deserializer);
    return QqMusicQrLoginUpdate(
      state: var_state,
      failure: var_failure,
      sessionActive: var_sessionActive,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    QqMusicOwnedPlaylistLoadHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicOwnedPlaylistLoadHandleImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicQrLoginSessionHandleImpl).frbInternalSseEncode(
        move: true,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    QqMusicOwnedPlaylistLoadHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicOwnedPlaylistLoadHandleImpl).frbInternalSseEncode(
        move: false,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicQrLoginSessionHandleImpl).frbInternalSseEncode(
        move: false,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicOwnedPlaylistLoadHandle(
    QqMusicOwnedPlaylistLoadHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicOwnedPlaylistLoadHandleImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QqMusicQrLoginSessionHandleImpl).frbInternalSseEncode(
        move: null,
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bootstrap_status(
    BootstrapStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.coreVersion, serializer);
    sse_encode_provider_status(self.provider, serializer);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_credential_export_failure(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_credential_restore_failure(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_credential_restore_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_credential_verification_failure(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_credential_verification_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_owned_playlist_load_failure(
    QqMusicOwnedPlaylistLoadFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_owned_playlist_load_failure(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_qr_challenge(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_qr_login_failure(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_qr_login_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_library_playlist_summary(
    LibraryPlaylistSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerId, serializer);
    sse_encode_String(self.opaqueId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artworkUri, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackCount, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_library_playlist_summary(
    List<LibraryPlaylistSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_library_playlist_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_credential_export_failure(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_credential_restore_failure(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_credential_restore_state(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_credential_verification_failure(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_credential_verification_state(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_owned_playlist_load_failure(
    QqMusicOwnedPlaylistLoadFailure? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_owned_playlist_load_failure(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_qr_challenge(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_qr_login_failure(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qq_music_qr_login_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_provider_status(
    ProviderStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_list_String(self.implementedCapabilities, serializer);
  }

  @protected
  void sse_encode_qq_music_credential_export(
    QqMusicCredentialExport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.secretBytes, serializer);
    sse_encode_opt_box_autoadd_qq_music_credential_export_failure(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_credential_restore(
    QqMusicCredentialRestore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_qq_music_credential_restore_state(
      self.state,
      serializer,
    );
    sse_encode_opt_box_autoadd_qq_music_credential_restore_failure(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_credential_verification(
    QqMusicCredentialVerification self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_qq_music_credential_verification_state(
      self.state,
      serializer,
    );
    sse_encode_opt_box_autoadd_qq_music_credential_verification_failure(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_owned_playlist_load(
    QqMusicOwnedPlaylistLoad self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_library_playlist_summary(self.playlists, serializer);
    sse_encode_opt_box_autoadd_qq_music_owned_playlist_load_failure(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_qq_music_owned_playlist_load_failure(
    QqMusicOwnedPlaylistLoadFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qq_music_qr_image_format(self.imageFormat, serializer);
    sse_encode_list_prim_u_8_strict(self.imageBytes, serializer);
  }

  @protected
  void sse_encode_qq_music_qr_image_format(
    QqMusicQrImageFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_qr_login_start(
    QqMusicQrLoginStart self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      self.session,
      serializer,
    );
    sse_encode_opt_box_autoadd_qq_music_qr_challenge(
      self.challenge,
      serializer,
    );
    sse_encode_opt_box_autoadd_qq_music_qr_login_failure(
      self.failure,
      serializer,
    );
  }

  @protected
  void sse_encode_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qq_music_qr_login_update(
    QqMusicQrLoginUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_qq_music_qr_login_state(self.state, serializer);
    sse_encode_opt_box_autoadd_qq_music_qr_login_failure(
      self.failure,
      serializer,
    );
    sse_encode_bool(self.sessionActive, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class QqMusicOwnedPlaylistLoadHandleImpl extends RustOpaque
    implements QqMusicOwnedPlaylistLoadHandle {
  // Not to be used by end users
  QqMusicOwnedPlaylistLoadHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  QqMusicOwnedPlaylistLoadHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_QqMusicOwnedPlaylistLoadHandle,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_QqMusicOwnedPlaylistLoadHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_QqMusicOwnedPlaylistLoadHandlePtr,
  );

  bool cancel() => RustLib.instance.api
      .crateApiLibraryQqMusicOwnedPlaylistLoadHandleCancel(that: this);

  bool get isActive => RustLib.instance.api
      .crateApiLibraryQqMusicOwnedPlaylistLoadHandleIsActive(that: this);

  Future<QqMusicOwnedPlaylistLoad> run() => RustLib.instance.api
      .crateApiLibraryQqMusicOwnedPlaylistLoadHandleRun(that: this);
}

@sealed
class QqMusicQrLoginSessionHandleImpl extends RustOpaque
    implements QqMusicQrLoginSessionHandle {
  // Not to be used by end users
  QqMusicQrLoginSessionHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  QqMusicQrLoginSessionHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_QqMusicQrLoginSessionHandle,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandlePtr,
  );

  Future<QqMusicQrLoginUpdate> advance() => RustLib.instance.api
      .crateApiAuthenticationQqMusicQrLoginSessionHandleAdvance(that: this);

  bool cancel() => RustLib.instance.api
      .crateApiAuthenticationQqMusicQrLoginSessionHandleCancel(that: this);

  bool get isActive => RustLib.instance.api
      .crateApiAuthenticationQqMusicQrLoginSessionHandleIsActive(that: this);
}
