// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/authentication.dart';
import 'api/bootstrap.dart';
import 'api/library.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicUserPlaylistLoadHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandlePtr;

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapStatus dco_decode_bootstrap_status(dynamic raw);

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicCredentialExportFailure
  dco_decode_box_autoadd_qq_music_credential_export_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_box_autoadd_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState
  dco_decode_box_autoadd_qq_music_credential_restore_state(dynamic raw);

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_box_autoadd_qq_music_credential_verification_failure(dynamic raw);

  @protected
  QqMusicCredentialVerificationState
  dco_decode_box_autoadd_qq_music_credential_verification_state(dynamic raw);

  @protected
  QqMusicQrChallenge dco_decode_box_autoadd_qq_music_qr_challenge(dynamic raw);

  @protected
  QqMusicQrLoginFailure dco_decode_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginState dco_decode_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadFailure
  dco_decode_box_autoadd_qq_music_user_playlist_load_failure(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LibraryPlaylistSummary dco_decode_library_playlist_summary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LibraryPlaylistSummary> dco_decode_list_library_playlist_summary(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  QqMusicQrLoginSessionHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicCredentialExportFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_export_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_state(dynamic raw);

  @protected
  QqMusicCredentialVerificationFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerificationState?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_state(
    dynamic raw,
  );

  @protected
  QqMusicQrChallenge? dco_decode_opt_box_autoadd_qq_music_qr_challenge(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginFailure? dco_decode_opt_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginState? dco_decode_opt_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_user_playlist_load_failure(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProviderStatus dco_decode_provider_status(dynamic raw);

  @protected
  QqMusicCredentialExport dco_decode_qq_music_credential_export(dynamic raw);

  @protected
  QqMusicCredentialExportFailure dco_decode_qq_music_credential_export_failure(
    dynamic raw,
  );

  @protected
  QqMusicCredentialRestore dco_decode_qq_music_credential_restore(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState dco_decode_qq_music_credential_restore_state(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerification dco_decode_qq_music_credential_verification(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_qq_music_credential_verification_failure(dynamic raw);

  @protected
  QqMusicCredentialVerificationState
  dco_decode_qq_music_credential_verification_state(dynamic raw);

  @protected
  QqMusicQrChallenge dco_decode_qq_music_qr_challenge(dynamic raw);

  @protected
  QqMusicQrImageFormat dco_decode_qq_music_qr_image_format(dynamic raw);

  @protected
  QqMusicQrLoginFailure dco_decode_qq_music_qr_login_failure(dynamic raw);

  @protected
  QqMusicQrLoginStart dco_decode_qq_music_qr_login_start(dynamic raw);

  @protected
  QqMusicQrLoginState dco_decode_qq_music_qr_login_state(dynamic raw);

  @protected
  QqMusicQrLoginUpdate dco_decode_qq_music_qr_login_update(dynamic raw);

  @protected
  QqMusicUserPlaylistLoad dco_decode_qq_music_user_playlist_load(dynamic raw);

  @protected
  QqMusicUserPlaylistLoadFailure dco_decode_qq_music_user_playlist_load_failure(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapStatus sse_decode_bootstrap_status(SseDeserializer deserializer);

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure
  sse_decode_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreState
  sse_decode_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState
  sse_decode_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge sse_decode_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure sse_decode_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState sse_decode_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure
  sse_decode_box_autoadd_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LibraryPlaylistSummary sse_decode_library_playlist_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LibraryPlaylistSummary> sse_decode_list_library_playlist_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  QqMusicQrLoginSessionHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreState?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge? sse_decode_opt_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure? sse_decode_opt_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState? sse_decode_opt_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProviderStatus sse_decode_provider_status(SseDeserializer deserializer);

  @protected
  QqMusicCredentialExport sse_decode_qq_music_credential_export(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure sse_decode_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestore sse_decode_qq_music_credential_restore(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_qq_music_credential_restore_failure(SseDeserializer deserializer);

  @protected
  QqMusicCredentialRestoreState sse_decode_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerification sse_decode_qq_music_credential_verification(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState
  sse_decode_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge sse_decode_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrImageFormat sse_decode_qq_music_qr_image_format(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure sse_decode_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginStart sse_decode_qq_music_qr_login_start(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState sse_decode_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginUpdate sse_decode_qq_music_qr_login_update(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoad sse_decode_qq_music_user_playlist_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure sse_decode_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_status(
    BootstrapStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_library_playlist_summary(
    LibraryPlaylistSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_playlist_summary(
    List<LibraryPlaylistSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_status(
    ProviderStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_export(
    QqMusicCredentialExport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore(
    QqMusicCredentialRestore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification(
    QqMusicCredentialVerification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_image_format(
    QqMusicQrImageFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_start(
    QqMusicQrLoginStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_update(
    QqMusicQrLoginUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_user_playlist_load(
    QqMusicUserPlaylistLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutterustmusic_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutterustmusic_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutterustmusic_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_flutterustmusic_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
