// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/album.dart';
import 'api/artist.dart';
import 'api/authentication.dart';
import 'api/bootstrap.dart';
import 'api/library.dart';
import 'api/lyrics.dart';
import 'api/media.dart';
import 'api/queue.dart';
import 'api/recommendations.dart';
import 'api/search.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PlaybackQueueHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicAlbumTrackPageLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicArtistTrackPageLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicLyricLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicMediaResolutionHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicPlaylistTrackPageLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicQrLoginSessionHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicRecommendedPlaylistPageLoadHandlePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicTrackSearchPageLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QqMusicUserPlaylistLoadHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle;

  @protected
  PlaybackQueueHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicLyricLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicMediaResolutionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    dynamic raw,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  PlaybackQueueHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicLyricLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicMediaResolutionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    dynamic raw,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  PlaybackQueueHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicLyricLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicMediaResolutionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    dynamic raw,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapStatus dco_decode_bootstrap_status(dynamic raw);

  @protected
  QqMusicQrLoginSessionHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  CatalogAlbumSummary dco_decode_box_autoadd_catalog_album_summary(dynamic raw);

  @protected
  LibraryTrackSummary dco_decode_box_autoadd_library_track_summary(dynamic raw);

  @protected
  PlaybackQueueFailure dco_decode_box_autoadd_playback_queue_failure(
    dynamic raw,
  );

  @protected
  PlaybackQueueSnapshot dco_decode_box_autoadd_playback_queue_snapshot(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure
  dco_decode_box_autoadd_qq_music_album_track_page_load_failure(dynamic raw);

  @protected
  QqMusicArtistTrackPageLoadFailure
  dco_decode_box_autoadd_qq_music_artist_track_page_load_failure(dynamic raw);

  @protected
  QqMusicCredentialExportFailure
  dco_decode_box_autoadd_qq_music_credential_export_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_box_autoadd_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState
  dco_decode_box_autoadd_qq_music_credential_restore_state(dynamic raw);

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_box_autoadd_qq_music_credential_verification_failure(dynamic raw);

  @protected
  QqMusicCredentialVerificationState
  dco_decode_box_autoadd_qq_music_credential_verification_state(dynamic raw);

  @protected
  QqMusicLyricLoadFailure dco_decode_box_autoadd_qq_music_lyric_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicMediaResolutionFailure
  dco_decode_box_autoadd_qq_music_media_resolution_failure(dynamic raw);

  @protected
  QqMusicPlaylistTrackPageLoadFailure
  dco_decode_box_autoadd_qq_music_playlist_track_page_load_failure(dynamic raw);

  @protected
  QqMusicQrChallenge dco_decode_box_autoadd_qq_music_qr_challenge(dynamic raw);

  @protected
  QqMusicQrLoginFailure dco_decode_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginState dco_decode_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure
  dco_decode_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicResolvedMediaSource
  dco_decode_box_autoadd_qq_music_resolved_media_source(dynamic raw);

  @protected
  QqMusicSynchronizedLyrics dco_decode_box_autoadd_qq_music_synchronized_lyrics(
    dynamic raw,
  );

  @protected
  QqMusicTrackSearchPageLoadFailure
  dco_decode_box_autoadd_qq_music_track_search_page_load_failure(dynamic raw);

  @protected
  QqMusicUserPlaylistLoadFailure
  dco_decode_box_autoadd_qq_music_user_playlist_load_failure(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CatalogAlbumSummary dco_decode_catalog_album_summary(dynamic raw);

  @protected
  CatalogArtistSummary dco_decode_catalog_artist_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LibraryPlaylistSummary dco_decode_library_playlist_summary(dynamic raw);

  @protected
  LibraryTrackSummary dco_decode_library_track_summary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CatalogArtistSummary> dco_decode_list_catalog_artist_summary(
    dynamic raw,
  );

  @protected
  List<LibraryPlaylistSummary> dco_decode_list_library_playlist_summary(
    dynamic raw,
  );

  @protected
  List<LibraryTrackSummary> dco_decode_list_library_track_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QqMusicSynchronizedLyricLine>
  dco_decode_list_qq_music_synchronized_lyric_line(dynamic raw);

  @protected
  List<QqMusicTimedLyricSegment> dco_decode_list_qq_music_timed_lyric_segment(
    dynamic raw,
  );

  @protected
  List<QqMusicTrackSearchItem> dco_decode_list_qq_music_track_search_item(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  QqMusicQrLoginSessionHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    dynamic raw,
  );

  @protected
  CatalogAlbumSummary? dco_decode_opt_box_autoadd_catalog_album_summary(
    dynamic raw,
  );

  @protected
  PlaybackQueueFailure? dco_decode_opt_box_autoadd_playback_queue_failure(
    dynamic raw,
  );

  @protected
  PlaybackQueueSnapshot? dco_decode_opt_box_autoadd_playback_queue_snapshot(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_album_track_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicArtistTrackPageLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_artist_track_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicCredentialExportFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_export_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState?
  dco_decode_opt_box_autoadd_qq_music_credential_restore_state(dynamic raw);

  @protected
  QqMusicCredentialVerificationFailure?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerificationState?
  dco_decode_opt_box_autoadd_qq_music_credential_verification_state(
    dynamic raw,
  );

  @protected
  QqMusicLyricLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_lyric_load_failure(dynamic raw);

  @protected
  QqMusicMediaResolutionFailure?
  dco_decode_opt_box_autoadd_qq_music_media_resolution_failure(dynamic raw);

  @protected
  QqMusicPlaylistTrackPageLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_playlist_track_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicQrChallenge? dco_decode_opt_box_autoadd_qq_music_qr_challenge(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginFailure? dco_decode_opt_box_autoadd_qq_music_qr_login_failure(
    dynamic raw,
  );

  @protected
  QqMusicQrLoginState? dco_decode_opt_box_autoadd_qq_music_qr_login_state(
    dynamic raw,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicResolvedMediaSource?
  dco_decode_opt_box_autoadd_qq_music_resolved_media_source(dynamic raw);

  @protected
  QqMusicSynchronizedLyrics?
  dco_decode_opt_box_autoadd_qq_music_synchronized_lyrics(dynamic raw);

  @protected
  QqMusicTrackSearchPageLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_track_search_page_load_failure(
    dynamic raw,
  );

  @protected
  QqMusicUserPlaylistLoadFailure?
  dco_decode_opt_box_autoadd_qq_music_user_playlist_load_failure(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PlaybackQueueFailure dco_decode_playback_queue_failure(dynamic raw);

  @protected
  PlaybackQueueSnapshot dco_decode_playback_queue_snapshot(dynamic raw);

  @protected
  PlaybackQueueUpdate dco_decode_playback_queue_update(dynamic raw);

  @protected
  ProviderStatus dco_decode_provider_status(dynamic raw);

  @protected
  QqMusicAlbumTrackPageLoad dco_decode_qq_music_album_track_page_load(
    dynamic raw,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure
  dco_decode_qq_music_album_track_page_load_failure(dynamic raw);

  @protected
  QqMusicArtistTrackPageLoad dco_decode_qq_music_artist_track_page_load(
    dynamic raw,
  );

  @protected
  QqMusicArtistTrackPageLoadFailure
  dco_decode_qq_music_artist_track_page_load_failure(dynamic raw);

  @protected
  QqMusicCredentialExport dco_decode_qq_music_credential_export(dynamic raw);

  @protected
  QqMusicCredentialExportFailure dco_decode_qq_music_credential_export_failure(
    dynamic raw,
  );

  @protected
  QqMusicCredentialRestore dco_decode_qq_music_credential_restore(dynamic raw);

  @protected
  QqMusicCredentialRestoreFailure
  dco_decode_qq_music_credential_restore_failure(dynamic raw);

  @protected
  QqMusicCredentialRestoreState dco_decode_qq_music_credential_restore_state(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerification dco_decode_qq_music_credential_verification(
    dynamic raw,
  );

  @protected
  QqMusicCredentialVerificationFailure
  dco_decode_qq_music_credential_verification_failure(dynamic raw);

  @protected
  QqMusicCredentialVerificationState
  dco_decode_qq_music_credential_verification_state(dynamic raw);

  @protected
  QqMusicLyricLoad dco_decode_qq_music_lyric_load(dynamic raw);

  @protected
  QqMusicLyricLoadFailure dco_decode_qq_music_lyric_load_failure(dynamic raw);

  @protected
  QqMusicMediaFormat dco_decode_qq_music_media_format(dynamic raw);

  @protected
  QqMusicMediaQuality dco_decode_qq_music_media_quality(dynamic raw);

  @protected
  QqMusicMediaResolution dco_decode_qq_music_media_resolution(dynamic raw);

  @protected
  QqMusicMediaResolutionFailure dco_decode_qq_music_media_resolution_failure(
    dynamic raw,
  );

  @protected
  QqMusicPlaylistTrackPageLoad dco_decode_qq_music_playlist_track_page_load(
    dynamic raw,
  );

  @protected
  QqMusicPlaylistTrackPageLoadFailure
  dco_decode_qq_music_playlist_track_page_load_failure(dynamic raw);

  @protected
  QqMusicQrChallenge dco_decode_qq_music_qr_challenge(dynamic raw);

  @protected
  QqMusicQrImageFormat dco_decode_qq_music_qr_image_format(dynamic raw);

  @protected
  QqMusicQrLoginFailure dco_decode_qq_music_qr_login_failure(dynamic raw);

  @protected
  QqMusicQrLoginStart dco_decode_qq_music_qr_login_start(dynamic raw);

  @protected
  QqMusicQrLoginState dco_decode_qq_music_qr_login_state(dynamic raw);

  @protected
  QqMusicQrLoginUpdate dco_decode_qq_music_qr_login_update(dynamic raw);

  @protected
  QqMusicRecommendedPlaylistPageLoad
  dco_decode_qq_music_recommended_playlist_page_load(dynamic raw);

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure
  dco_decode_qq_music_recommended_playlist_page_load_failure(dynamic raw);

  @protected
  QqMusicResolvedMediaSource dco_decode_qq_music_resolved_media_source(
    dynamic raw,
  );

  @protected
  QqMusicSynchronizedLyricLine dco_decode_qq_music_synchronized_lyric_line(
    dynamic raw,
  );

  @protected
  QqMusicSynchronizedLyrics dco_decode_qq_music_synchronized_lyrics(
    dynamic raw,
  );

  @protected
  QqMusicTimedLyricSegment dco_decode_qq_music_timed_lyric_segment(dynamic raw);

  @protected
  QqMusicTrackSearchItem dco_decode_qq_music_track_search_item(dynamic raw);

  @protected
  QqMusicTrackSearchPageLoad dco_decode_qq_music_track_search_page_load(
    dynamic raw,
  );

  @protected
  QqMusicTrackSearchPageLoadFailure
  dco_decode_qq_music_track_search_page_load_failure(dynamic raw);

  @protected
  QqMusicUserPlaylistLoad dco_decode_qq_music_user_playlist_load(dynamic raw);

  @protected
  QqMusicUserPlaylistLoadFailure dco_decode_qq_music_user_playlist_load_failure(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  PlaybackQueueHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapStatus sse_decode_bootstrap_status(SseDeserializer deserializer);

  @protected
  QqMusicQrLoginSessionHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  CatalogAlbumSummary sse_decode_box_autoadd_catalog_album_summary(
    SseDeserializer deserializer,
  );

  @protected
  LibraryTrackSummary sse_decode_box_autoadd_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueFailure sse_decode_box_autoadd_playback_queue_failure(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueSnapshot sse_decode_box_autoadd_playback_queue_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure
  sse_decode_box_autoadd_qq_music_album_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadFailure
  sse_decode_box_autoadd_qq_music_artist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure
  sse_decode_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreState
  sse_decode_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState
  sse_decode_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoadFailure sse_decode_box_autoadd_qq_music_lyric_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionFailure
  sse_decode_box_autoadd_qq_music_media_resolution_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadFailure
  sse_decode_box_autoadd_qq_music_playlist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge sse_decode_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure sse_decode_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState sse_decode_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure
  sse_decode_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicResolvedMediaSource
  sse_decode_box_autoadd_qq_music_resolved_media_source(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicSynchronizedLyrics sse_decode_box_autoadd_qq_music_synchronized_lyrics(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadFailure
  sse_decode_box_autoadd_qq_music_track_search_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure
  sse_decode_box_autoadd_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CatalogAlbumSummary sse_decode_catalog_album_summary(
    SseDeserializer deserializer,
  );

  @protected
  CatalogArtistSummary sse_decode_catalog_artist_summary(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LibraryPlaylistSummary sse_decode_library_playlist_summary(
    SseDeserializer deserializer,
  );

  @protected
  LibraryTrackSummary sse_decode_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CatalogArtistSummary> sse_decode_list_catalog_artist_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<LibraryPlaylistSummary> sse_decode_list_library_playlist_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<LibraryTrackSummary> sse_decode_list_library_track_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QqMusicSynchronizedLyricLine>
  sse_decode_list_qq_music_synchronized_lyric_line(
    SseDeserializer deserializer,
  );

  @protected
  List<QqMusicTimedLyricSegment> sse_decode_list_qq_music_timed_lyric_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<QqMusicTrackSearchItem> sse_decode_list_qq_music_track_search_item(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  QqMusicQrLoginSessionHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  CatalogAlbumSummary? sse_decode_opt_box_autoadd_catalog_album_summary(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueFailure? sse_decode_opt_box_autoadd_playback_queue_failure(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueSnapshot? sse_decode_opt_box_autoadd_playback_queue_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_album_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_artist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreState?
  sse_decode_opt_box_autoadd_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState?
  sse_decode_opt_box_autoadd_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_lyric_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionFailure?
  sse_decode_opt_box_autoadd_qq_music_media_resolution_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_playlist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge? sse_decode_opt_box_autoadd_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure? sse_decode_opt_box_autoadd_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState? sse_decode_opt_box_autoadd_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicResolvedMediaSource?
  sse_decode_opt_box_autoadd_qq_music_resolved_media_source(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicSynchronizedLyrics?
  sse_decode_opt_box_autoadd_qq_music_synchronized_lyrics(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_track_search_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure?
  sse_decode_opt_box_autoadd_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PlaybackQueueFailure sse_decode_playback_queue_failure(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueSnapshot sse_decode_playback_queue_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackQueueUpdate sse_decode_playback_queue_update(
    SseDeserializer deserializer,
  );

  @protected
  ProviderStatus sse_decode_provider_status(SseDeserializer deserializer);

  @protected
  QqMusicAlbumTrackPageLoad sse_decode_qq_music_album_track_page_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicAlbumTrackPageLoadFailure
  sse_decode_qq_music_album_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoad sse_decode_qq_music_artist_track_page_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicArtistTrackPageLoadFailure
  sse_decode_qq_music_artist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExport sse_decode_qq_music_credential_export(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialExportFailure sse_decode_qq_music_credential_export_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestore sse_decode_qq_music_credential_restore(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialRestoreFailure
  sse_decode_qq_music_credential_restore_failure(SseDeserializer deserializer);

  @protected
  QqMusicCredentialRestoreState sse_decode_qq_music_credential_restore_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerification sse_decode_qq_music_credential_verification(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationFailure
  sse_decode_qq_music_credential_verification_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicCredentialVerificationState
  sse_decode_qq_music_credential_verification_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicLyricLoad sse_decode_qq_music_lyric_load(SseDeserializer deserializer);

  @protected
  QqMusicLyricLoadFailure sse_decode_qq_music_lyric_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaFormat sse_decode_qq_music_media_format(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaQuality sse_decode_qq_music_media_quality(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolution sse_decode_qq_music_media_resolution(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicMediaResolutionFailure sse_decode_qq_music_media_resolution_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoad sse_decode_qq_music_playlist_track_page_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicPlaylistTrackPageLoadFailure
  sse_decode_qq_music_playlist_track_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrChallenge sse_decode_qq_music_qr_challenge(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrImageFormat sse_decode_qq_music_qr_image_format(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginFailure sse_decode_qq_music_qr_login_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginStart sse_decode_qq_music_qr_login_start(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginState sse_decode_qq_music_qr_login_state(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicQrLoginUpdate sse_decode_qq_music_qr_login_update(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoad
  sse_decode_qq_music_recommended_playlist_page_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicRecommendedPlaylistPageLoadFailure
  sse_decode_qq_music_recommended_playlist_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicResolvedMediaSource sse_decode_qq_music_resolved_media_source(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicSynchronizedLyricLine sse_decode_qq_music_synchronized_lyric_line(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicSynchronizedLyrics sse_decode_qq_music_synchronized_lyrics(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTimedLyricSegment sse_decode_qq_music_timed_lyric_segment(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchItem sse_decode_qq_music_track_search_item(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoad sse_decode_qq_music_track_search_page_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicTrackSearchPageLoadFailure
  sse_decode_qq_music_track_search_page_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoad sse_decode_qq_music_user_playlist_load(
    SseDeserializer deserializer,
  );

  @protected
  QqMusicUserPlaylistLoadFailure sse_decode_qq_music_user_playlist_load_failure(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    PlaybackQueueHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    QqMusicAlbumTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    QqMusicArtistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    QqMusicLyricLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    QqMusicMediaResolutionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    QqMusicPlaylistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    QqMusicRecommendedPlaylistPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    QqMusicTrackSearchPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    PlaybackQueueHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    QqMusicAlbumTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    QqMusicArtistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    QqMusicLyricLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    QqMusicMediaResolutionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    QqMusicPlaylistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    QqMusicRecommendedPlaylistPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    QqMusicTrackSearchPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    PlaybackQueueHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    QqMusicAlbumTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    QqMusicArtistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    QqMusicLyricLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    QqMusicMediaResolutionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    QqMusicPlaylistTrackPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    QqMusicRecommendedPlaylistPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    QqMusicTrackSearchPageLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    QqMusicUserPlaylistLoadHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_status(
    BootstrapStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_catalog_album_summary(
    CatalogAlbumSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_library_track_summary(
    LibraryTrackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playback_queue_failure(
    PlaybackQueueFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playback_queue_snapshot(
    PlaybackQueueSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_album_track_page_load_failure(
    QqMusicAlbumTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_artist_track_page_load_failure(
    QqMusicArtistTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_lyric_load_failure(
    QqMusicLyricLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_media_resolution_failure(
    QqMusicMediaResolutionFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_playlist_track_page_load_failure(
    QqMusicPlaylistTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    QqMusicRecommendedPlaylistPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_resolved_media_source(
    QqMusicResolvedMediaSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_synchronized_lyrics(
    QqMusicSynchronizedLyrics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_track_search_page_load_failure(
    QqMusicTrackSearchPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_album_summary(
    CatalogAlbumSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_artist_summary(
    CatalogArtistSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_library_playlist_summary(
    LibraryPlaylistSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_track_summary(
    LibraryTrackSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_catalog_artist_summary(
    List<CatalogArtistSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_playlist_summary(
    List<LibraryPlaylistSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_track_summary(
    List<LibraryTrackSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_qq_music_synchronized_lyric_line(
    List<QqMusicSynchronizedLyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_qq_music_timed_lyric_segment(
    List<QqMusicTimedLyricSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_qq_music_track_search_item(
    List<QqMusicTrackSearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    QqMusicQrLoginSessionHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_catalog_album_summary(
    CatalogAlbumSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_playback_queue_failure(
    PlaybackQueueFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_playback_queue_snapshot(
    PlaybackQueueSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_album_track_page_load_failure(
    QqMusicAlbumTrackPageLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_artist_track_page_load_failure(
    QqMusicArtistTrackPageLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_lyric_load_failure(
    QqMusicLyricLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_media_resolution_failure(
    QqMusicMediaResolutionFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_playlist_track_page_load_failure(
    QqMusicPlaylistTrackPageLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_challenge(
    QqMusicQrChallenge? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_failure(
    QqMusicQrLoginFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_qr_login_state(
    QqMusicQrLoginState? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_qq_music_recommended_playlist_page_load_failure(
    QqMusicRecommendedPlaylistPageLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_resolved_media_source(
    QqMusicResolvedMediaSource? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_synchronized_lyrics(
    QqMusicSynchronizedLyrics? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_track_search_page_load_failure(
    QqMusicTrackSearchPageLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_queue_failure(
    PlaybackQueueFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_queue_snapshot(
    PlaybackQueueSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_queue_update(
    PlaybackQueueUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_status(
    ProviderStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_album_track_page_load(
    QqMusicAlbumTrackPageLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_album_track_page_load_failure(
    QqMusicAlbumTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_artist_track_page_load(
    QqMusicArtistTrackPageLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_artist_track_page_load_failure(
    QqMusicArtistTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_export(
    QqMusicCredentialExport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_export_failure(
    QqMusicCredentialExportFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore(
    QqMusicCredentialRestore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore_failure(
    QqMusicCredentialRestoreFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_restore_state(
    QqMusicCredentialRestoreState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification(
    QqMusicCredentialVerification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification_failure(
    QqMusicCredentialVerificationFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_credential_verification_state(
    QqMusicCredentialVerificationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_lyric_load(
    QqMusicLyricLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_lyric_load_failure(
    QqMusicLyricLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_media_format(
    QqMusicMediaFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_media_quality(
    QqMusicMediaQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_media_resolution(
    QqMusicMediaResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_media_resolution_failure(
    QqMusicMediaResolutionFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_playlist_track_page_load(
    QqMusicPlaylistTrackPageLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_playlist_track_page_load_failure(
    QqMusicPlaylistTrackPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_challenge(
    QqMusicQrChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_image_format(
    QqMusicQrImageFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_failure(
    QqMusicQrLoginFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_start(
    QqMusicQrLoginStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_state(
    QqMusicQrLoginState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_qr_login_update(
    QqMusicQrLoginUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_recommended_playlist_page_load(
    QqMusicRecommendedPlaylistPageLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_recommended_playlist_page_load_failure(
    QqMusicRecommendedPlaylistPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_resolved_media_source(
    QqMusicResolvedMediaSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_synchronized_lyric_line(
    QqMusicSynchronizedLyricLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_synchronized_lyrics(
    QqMusicSynchronizedLyrics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_timed_lyric_segment(
    QqMusicTimedLyricSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_track_search_item(
    QqMusicTrackSearchItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_track_search_page_load(
    QqMusicTrackSearchPageLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_track_search_page_load_failure(
    QqMusicTrackSearchPageLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_user_playlist_load(
    QqMusicUserPlaylistLoad self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qq_music_user_playlist_load_failure(
    QqMusicUserPlaylistLoadFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlaybackQueueHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicAlbumTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicArtistTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicLyricLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicMediaResolutionHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicPlaylistTrackPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicQrLoginSessionHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicRecommendedPlaylistPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicTrackSearchPageLoadHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQqMusicUserPlaylistLoadHandle(
    int ptr,
  );
}
