// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `album_id`, `bridge_album_summary`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicAlbumTrackPageLoadHandle beginQqMusicAlbumTrackPageLoad({
  required String providerId,
  required String opaqueAlbumId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiAlbumBeginQqMusicAlbumTrackPageLoad(
  providerId: providerId,
  opaqueAlbumId: opaqueAlbumId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicAlbumTrackPageLoadHandle>>
abstract class QqMusicAlbumTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicAlbumTrackPageLoad> run();
}

class CatalogAlbumSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? artworkUri;

  const CatalogAlbumSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.artworkUri,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artworkUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogAlbumSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artworkUri == other.artworkUri;
}

class QqMusicAlbumTrackPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicAlbumTrackPageLoadFailure? failure;

  const QqMusicAlbumTrackPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicAlbumTrackPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicAlbumTrackPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
