// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'artist.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `album_id`, `bridge_album_summary`, `failed_details_load`, `failed_load`, `map_details_error`, `map_details_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicAlbumDetailsLoadHandle beginQqMusicAlbumDetailsLoad({
  required String providerId,
  required String opaqueAlbumId,
}) => RustLib.instance.api.crateApiAlbumBeginQqMusicAlbumDetailsLoad(
  providerId: providerId,
  opaqueAlbumId: opaqueAlbumId,
);

QqMusicAlbumTrackPageLoadHandle beginQqMusicAlbumTrackPageLoad({
  required String providerId,
  required String opaqueAlbumId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiAlbumBeginQqMusicAlbumTrackPageLoad(
  providerId: providerId,
  opaqueAlbumId: opaqueAlbumId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicAlbumDetailsLoadHandle>>
abstract class QqMusicAlbumDetailsLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicAlbumDetailsLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicAlbumTrackPageLoadHandle>>
abstract class QqMusicAlbumTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicAlbumTrackPageLoad> run();
}

class CatalogAlbumDetails {
  final CatalogAlbumSummary album;
  final List<CatalogArtistSummary> artists;
  final String? subtitle;
  final String? releaseDate;
  final String? description;
  final String? language;
  final String? albumType;
  final String? genre;
  final String? company;

  const CatalogAlbumDetails({
    required this.album,
    required this.artists,
    this.subtitle,
    this.releaseDate,
    this.description,
    this.language,
    this.albumType,
    this.genre,
    this.company,
  });

  @override
  int get hashCode =>
      album.hashCode ^
      artists.hashCode ^
      subtitle.hashCode ^
      releaseDate.hashCode ^
      description.hashCode ^
      language.hashCode ^
      albumType.hashCode ^
      genre.hashCode ^
      company.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogAlbumDetails &&
          runtimeType == other.runtimeType &&
          album == other.album &&
          artists == other.artists &&
          subtitle == other.subtitle &&
          releaseDate == other.releaseDate &&
          description == other.description &&
          language == other.language &&
          albumType == other.albumType &&
          genre == other.genre &&
          company == other.company;
}

class CatalogAlbumSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? artworkUri;

  const CatalogAlbumSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.artworkUri,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artworkUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogAlbumSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artworkUri == other.artworkUri;
}

class QqMusicAlbumDetailsLoad {
  final CatalogAlbumDetails? details;
  final QqMusicAlbumDetailsLoadFailure? failure;

  const QqMusicAlbumDetailsLoad({this.details, this.failure});

  @override
  int get hashCode => details.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicAlbumDetailsLoad &&
          runtimeType == other.runtimeType &&
          details == other.details &&
          failure == other.failure;
}

enum QqMusicAlbumDetailsLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}

class QqMusicAlbumTrackPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicAlbumTrackPageLoadFailure? failure;

  const QqMusicAlbumTrackPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicAlbumTrackPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicAlbumTrackPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
