// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `artist_id`, `bridge_artist_summary`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicArtistTrackPageLoadHandle beginQqMusicArtistTrackPageLoad({
  required String providerId,
  required String opaqueArtistId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiArtistBeginQqMusicArtistTrackPageLoad(
  providerId: providerId,
  opaqueArtistId: opaqueArtistId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicArtistTrackPageLoadHandle>>
abstract class QqMusicArtistTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicArtistTrackPageLoad> run();
}

class CatalogArtistSummary {
  final String providerId;
  final String opaqueId;
  final String name;

  const CatalogArtistSummary({
    required this.providerId,
    required this.opaqueId,
    required this.name,
  });

  @override
  int get hashCode => providerId.hashCode ^ opaqueId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogArtistSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          name == other.name;
}

class QqMusicArtistTrackPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicArtistTrackPageLoadFailure? failure;

  const QqMusicArtistTrackPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicArtistTrackPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicArtistTrackPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
