// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_start_attempt`, `failed_start`, `map_error`, `map_progress`, `start_attempt_guard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

int reserveQqMusicWechatQrLoginStart() => RustLib.instance.api
    .crateApiAuthenticationReserveQqMusicWechatQrLoginStart();

Future<QqMusicQrLoginStart> startQqMusicWechatQrLogin({
  required int attemptId,
}) => RustLib.instance.api.crateApiAuthenticationStartQqMusicWechatQrLogin(
  attemptId: attemptId,
);

bool cancelQqMusicWechatQrLoginStart({required int attemptId}) =>
    RustLib.instance.api.crateApiAuthenticationCancelQqMusicWechatQrLoginStart(
      attemptId: attemptId,
    );

bool qqMusicHasAuthenticatedCredential() => RustLib.instance.api
    .crateApiAuthenticationQqMusicHasAuthenticatedCredential();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicQrLoginSessionHandle>>
abstract class QqMusicQrLoginSessionHandle implements RustOpaqueInterface {
  Future<QqMusicQrLoginUpdate> advance();

  bool cancel();

  bool get isActive;
}

class QqMusicQrChallenge {
  final QqMusicQrImageFormat imageFormat;
  final Uint8List imageBytes;

  const QqMusicQrChallenge({
    required this.imageFormat,
    required this.imageBytes,
  });

  @override
  int get hashCode => imageFormat.hashCode ^ imageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrChallenge &&
          runtimeType == other.runtimeType &&
          imageFormat == other.imageFormat &&
          imageBytes == other.imageBytes;
}

enum QqMusicQrImageFormat { png, jpeg }

enum QqMusicQrLoginFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  rejected,
  cancelled,
  replaced,
  sessionClosed,
  sessionFinished,
  timedOut,
  tooManyNetworkFailures,
  advanceAlreadyInProgress,
}

class QqMusicQrLoginStart {
  final QqMusicQrLoginSessionHandle? session;
  final QqMusicQrChallenge? challenge;
  final QqMusicQrLoginFailure? failure;

  const QqMusicQrLoginStart({this.session, this.challenge, this.failure});

  @override
  int get hashCode => session.hashCode ^ challenge.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrLoginStart &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          challenge == other.challenge &&
          failure == other.failure;
}

enum QqMusicQrLoginState {
  waitingForScan,
  scannedAwaitingConfirmation,
  authenticated,
  expired,
  refused,
  timedOut,
}

class QqMusicQrLoginUpdate {
  final QqMusicQrLoginState? state;
  final QqMusicQrLoginFailure? failure;
  final bool sessionActive;

  const QqMusicQrLoginUpdate({
    this.state,
    this.failure,
    required this.sessionActive,
  });

  @override
  int get hashCode =>
      state.hashCode ^ failure.hashCode ^ sessionActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrLoginUpdate &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          failure == other.failure &&
          sessionActive == other.sessionActive;
}
