// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_desktop_quick_start_attempt`, `clear_start_attempt`, `desktop_quick_start_attempt_guard`, `failed_account_summary`, `failed_desktop_quick_start`, `failed_desktop_quick_update`, `failed_restore`, `failed_start`, `failed_verification`, `map_account_summary_failure`, `map_account_summary_load`, `map_desktop_quick_failure`, `map_error`, `map_persistence_error`, `map_progress`, `map_restore_state`, `map_verification_failure`, `native_qq_music_provider`, `start_attempt_guard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

int reserveQqMusicDesktopQuickLoginStart() => RustLib.instance.api
    .crateApiAuthenticationReserveQqMusicDesktopQuickLoginStart();

Future<QqMusicDesktopQuickLoginStart> startQqMusicDesktopQuickLogin({
  required int attemptId,
}) => RustLib.instance.api.crateApiAuthenticationStartQqMusicDesktopQuickLogin(
  attemptId: attemptId,
);

bool cancelQqMusicDesktopQuickLoginStart({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiAuthenticationCancelQqMusicDesktopQuickLoginStart(
      attemptId: attemptId,
    );

int reserveQqMusicWechatQrLoginStart() => RustLib.instance.api
    .crateApiAuthenticationReserveQqMusicWechatQrLoginStart();

int reserveQqMusicQrLoginStart() =>
    RustLib.instance.api.crateApiAuthenticationReserveQqMusicQrLoginStart();

Future<QqMusicQrLoginStart> startQqMusicWechatQrLogin({
  required int attemptId,
}) => RustLib.instance.api.crateApiAuthenticationStartQqMusicWechatQrLogin(
  attemptId: attemptId,
);

Future<QqMusicQrLoginStart> startQqMusicQrLogin({
  required int attemptId,
  required QqMusicQrLoginChannel channel,
}) => RustLib.instance.api.crateApiAuthenticationStartQqMusicQrLogin(
  attemptId: attemptId,
  channel: channel,
);

bool cancelQqMusicWechatQrLoginStart({required int attemptId}) =>
    RustLib.instance.api.crateApiAuthenticationCancelQqMusicWechatQrLoginStart(
      attemptId: attemptId,
    );

bool cancelQqMusicQrLoginStart({required int attemptId}) => RustLib.instance.api
    .crateApiAuthenticationCancelQqMusicQrLoginStart(attemptId: attemptId);

bool qqMusicHasAuthenticatedCredential() => RustLib.instance.api
    .crateApiAuthenticationQqMusicHasAuthenticatedCredential();

QqMusicAccountSummaryLoadHandle beginQqMusicAccountSummaryLoad() =>
    RustLib.instance.api.crateApiAuthenticationBeginQqMusicAccountSummaryLoad();

/// Clears the process-local QQ Music credential and cancels authentication
/// work. The Flutter platform edge deletes the separately stored vault entry
/// only after this succeeds.
bool signOutQqMusic() =>
    RustLib.instance.api.crateApiAuthenticationSignOutQqMusic();

/// Produces a short-lived secret payload for immediate handoff to the platform
/// secure-storage plugin. Do not log, cache, or retain the returned bytes.
QqMusicCredentialExport exportQqMusicCredentialForSecureStorage() => RustLib
    .instance
    .api
    .crateApiAuthenticationExportQqMusicCredentialForSecureStorage();

/// Imports an optional platform-vault document into Rust and returns only the
/// safe next action. A present document is never considered authenticated
/// until a later QQ Music server-verification step succeeds.
QqMusicCredentialRestore restoreQqMusicCredentialFromSecureStorage({
  Uint8List? secretBytes,
}) => RustLib.instance.api
    .crateApiAuthenticationRestoreQqMusicCredentialFromSecureStorage(
      secretBytes: secretBytes,
    );

int? reserveQqMusicCredentialVerification() => RustLib.instance.api
    .crateApiAuthenticationReserveQqMusicCredentialVerification();

Future<QqMusicCredentialVerification> verifyRestoredQqMusicCredential({
  required int attemptId,
}) =>
    RustLib.instance.api.crateApiAuthenticationVerifyRestoredQqMusicCredential(
      attemptId: attemptId,
    );

bool cancelQqMusicCredentialVerification({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiAuthenticationCancelQqMusicCredentialVerification(
      attemptId: attemptId,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicAccountSummaryLoadHandle>>
abstract class QqMusicAccountSummaryLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicAccountSummaryLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicDesktopQuickLoginSessionHandle>>
abstract class QqMusicDesktopQuickLoginSessionHandle
    implements RustOpaqueInterface {
  Future<QqMusicDesktopQuickLoginUpdate> authorize({required int selectionId});

  bool cancel();

  bool get isActive;
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicQrLoginSessionHandle>>
abstract class QqMusicQrLoginSessionHandle implements RustOpaqueInterface {
  Future<QqMusicQrLoginUpdate> advance();

  bool cancel();

  bool get isActive;
}

class QqMusicAccountSummary {
  final String displayName;
  final String? avatarUri;

  const QqMusicAccountSummary({required this.displayName, this.avatarUri});

  @override
  int get hashCode => displayName.hashCode ^ avatarUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicAccountSummary &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          avatarUri == other.avatarUri;
}

enum QqMusicAccountSummaryFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

class QqMusicAccountSummaryLoad {
  final QqMusicAccountSummary? summary;
  final QqMusicAccountSummaryFailure? failure;

  const QqMusicAccountSummaryLoad({this.summary, this.failure});

  @override
  int get hashCode => summary.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicAccountSummaryLoad &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          failure == other.failure;
}

class QqMusicCredentialExport {
  final Uint8List? secretBytes;
  final QqMusicCredentialExportFailure? failure;

  const QqMusicCredentialExport({this.secretBytes, this.failure});

  @override
  int get hashCode => secretBytes.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicCredentialExport &&
          runtimeType == other.runtimeType &&
          secretBytes == other.secretBytes &&
          failure == other.failure;
}

enum QqMusicCredentialExportFailure {
  noAuthenticatedCredential,
  serializationFailed,
}

class QqMusicCredentialRestore {
  final QqMusicCredentialRestoreState? state;
  final QqMusicCredentialRestoreFailure? failure;

  const QqMusicCredentialRestore({this.state, this.failure});

  @override
  int get hashCode => state.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicCredentialRestore &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          failure == other.failure;
}

enum QqMusicCredentialRestoreFailure {
  coreUnavailable,
  invalidDocument,
  unsupportedVersion,
  invalidCredential,
}

enum QqMusicCredentialRestoreState {
  signedOut,
  verificationRequired,
  locallyExpired,
}

class QqMusicCredentialVerification {
  final QqMusicCredentialVerificationState? state;
  final QqMusicCredentialVerificationFailure? failure;

  const QqMusicCredentialVerification({this.state, this.failure});

  @override
  int get hashCode => state.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicCredentialVerification &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          failure == other.failure;
}

enum QqMusicCredentialVerificationFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  noRestoredCredential,
  replaced,
}

enum QqMusicCredentialVerificationState { authenticated, rejected }

class QqMusicDesktopQuickLoginAccount {
  final int selectionId;
  final String displayName;
  final String accountHint;

  const QqMusicDesktopQuickLoginAccount({
    required this.selectionId,
    required this.displayName,
    required this.accountHint,
  });

  @override
  int get hashCode =>
      selectionId.hashCode ^ displayName.hashCode ^ accountHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicDesktopQuickLoginAccount &&
          runtimeType == other.runtimeType &&
          selectionId == other.selectionId &&
          displayName == other.displayName &&
          accountHint == other.accountHint;
}

enum QqMusicDesktopQuickLoginFailure {
  coreUnavailable,
  clientUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  invalidSelection,
  rejected,
  cancelled,
  replaced,
  sessionFinished,
  alreadyRunning,
}

class QqMusicDesktopQuickLoginStart {
  final QqMusicDesktopQuickLoginSessionHandle? session;
  final List<QqMusicDesktopQuickLoginAccount> accounts;
  final QqMusicDesktopQuickLoginFailure? failure;

  const QqMusicDesktopQuickLoginStart({
    this.session,
    required this.accounts,
    this.failure,
  });

  @override
  int get hashCode => session.hashCode ^ accounts.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicDesktopQuickLoginStart &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          accounts == other.accounts &&
          failure == other.failure;
}

class QqMusicDesktopQuickLoginUpdate {
  final bool authenticated;
  final QqMusicDesktopQuickLoginFailure? failure;
  final bool sessionActive;

  const QqMusicDesktopQuickLoginUpdate({
    required this.authenticated,
    this.failure,
    required this.sessionActive,
  });

  @override
  int get hashCode =>
      authenticated.hashCode ^ failure.hashCode ^ sessionActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicDesktopQuickLoginUpdate &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          failure == other.failure &&
          sessionActive == other.sessionActive;
}

class QqMusicQrChallenge {
  final QqMusicQrImageFormat imageFormat;
  final Uint8List imageBytes;

  const QqMusicQrChallenge({
    required this.imageFormat,
    required this.imageBytes,
  });

  @override
  int get hashCode => imageFormat.hashCode ^ imageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrChallenge &&
          runtimeType == other.runtimeType &&
          imageFormat == other.imageFormat &&
          imageBytes == other.imageBytes;
}

enum QqMusicQrImageFormat { png, jpeg }

enum QqMusicQrLoginChannel { qq, wechat }

enum QqMusicQrLoginFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  rejected,
  cancelled,
  replaced,
  sessionClosed,
  sessionFinished,
  timedOut,
  tooManyNetworkFailures,
  advanceAlreadyInProgress,
}

class QqMusicQrLoginStart {
  final QqMusicQrLoginSessionHandle? session;
  final QqMusicQrChallenge? challenge;
  final QqMusicQrLoginFailure? failure;

  const QqMusicQrLoginStart({this.session, this.challenge, this.failure});

  @override
  int get hashCode => session.hashCode ^ challenge.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrLoginStart &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          challenge == other.challenge &&
          failure == other.failure;
}

enum QqMusicQrLoginState {
  waitingForScan,
  scannedAwaitingConfirmation,
  authenticated,
  expired,
  refused,
  timedOut,
}

class QqMusicQrLoginUpdate {
  final QqMusicQrLoginState? state;
  final QqMusicQrLoginFailure? failure;
  final bool sessionActive;

  const QqMusicQrLoginUpdate({
    this.state,
    this.failure,
    required this.sessionActive,
  });

  @override
  int get hashCode =>
      state.hashCode ^ failure.hashCode ^ sessionActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicQrLoginUpdate &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          failure == other.failure &&
          sessionActive == other.sessionActive;
}
