// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

BootstrapStatus bootstrapStatus() =>
    RustLib.instance.api.crateApiBootstrapBootstrapStatus();

/// Presentation-safe startup information used to prove the bridge boundary.
class BootstrapStatus {
  final String coreVersion;
  final ProviderStatus provider;

  const BootstrapStatus({required this.coreVersion, required this.provider});

  @override
  int get hashCode => coreVersion.hashCode ^ provider.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapStatus &&
          runtimeType == other.runtimeType &&
          coreVersion == other.coreVersion &&
          provider == other.provider;
}

class ProviderStatus {
  final String id;
  final String displayName;
  final List<String> implementedCapabilities;

  const ProviderStatus({
    required this.id,
    required this.displayName,
    required this.implementedCapabilities,
  });

  @override
  int get hashCode =>
      id.hashCode ^ displayName.hashCode ^ implementedCapabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderStatus &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          implementedCapabilities == other.implementedCapabilities;
}
