// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_comment`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicTrackCommentPageLoadHandle beginQqMusicTrackCommentPageLoad({
  required String providerId,
  required String opaqueTrackId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiCommentsBeginQqMusicTrackCommentPageLoad(
  providerId: providerId,
  opaqueTrackId: opaqueTrackId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicTrackCommentPageLoadHandle>>
abstract class QqMusicTrackCommentPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicTrackCommentPageLoad> run();
}

class QqMusicTrackCommentPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<TrackCommentSummary> hotComments;
  final List<TrackCommentSummary> latestComments;
  final QqMusicTrackCommentPageLoadFailure? failure;

  const QqMusicTrackCommentPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.hotComments,
    required this.latestComments,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      hotComments.hashCode ^
      latestComments.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicTrackCommentPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          hotComments == other.hotComments &&
          latestComments == other.latestComments &&
          failure == other.failure;
}

enum QqMusicTrackCommentPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}

class TrackCommentSummary {
  final String providerId;
  final String opaqueId;
  final String authorDisplayName;
  final String content;
  final int publishedAtUnixSeconds;
  final int praiseCount;

  const TrackCommentSummary({
    required this.providerId,
    required this.opaqueId,
    required this.authorDisplayName,
    required this.content,
    required this.publishedAtUnixSeconds,
    required this.praiseCount,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      authorDisplayName.hashCode ^
      content.hashCode ^
      publishedAtUnixSeconds.hashCode ^
      praiseCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackCommentSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          authorDisplayName == other.authorDisplayName &&
          content == other.content &&
          publishedAtUnixSeconds == other.publishedAtUnixSeconds &&
          praiseCount == other.praiseCount;
}
