// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'artist.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

QqMusicFavoriteArtistPageLoadHandle beginQqMusicFavoriteArtistPageLoad({
  required int offset,
  required int size,
}) => RustLib.instance.api
    .crateApiFavoriteArtistsBeginQqMusicFavoriteArtistPageLoad(
      offset: offset,
      size: size,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicFavoriteArtistPageLoadHandle>>
abstract class QqMusicFavoriteArtistPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicFavoriteArtistPageLoad> run();
}

class QqMusicFavoriteArtistPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<CatalogArtistSummary> artists;
  final QqMusicFavoriteArtistPageLoadFailure? failure;

  const QqMusicFavoriteArtistPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.artists,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      artists.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicFavoriteArtistPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          artists == other.artists &&
          failure == other.failure;
}

enum QqMusicFavoriteArtistPageLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}
