// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

QqMusicFavoriteAlbumPageLoadHandle beginQqMusicFavoriteAlbumPageLoad({
  required String providerId,
  required int offset,
  required int size,
}) => RustLib.instance.api
    .crateApiFavoriteAlbumsBeginQqMusicFavoriteAlbumPageLoad(
      providerId: providerId,
      offset: offset,
      size: size,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicFavoriteAlbumPageLoadHandle>>
abstract class QqMusicFavoriteAlbumPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicFavoriteAlbumPageLoad> run();
}

class QqMusicFavoriteAlbumPageLoad {
  final int offset;
  final int nextOffset;
  final int total;
  final bool hasMore;
  final int omittedAlbumCount;
  final List<CatalogAlbumSummary> albums;
  final QqMusicFavoriteAlbumPageLoadFailure? failure;

  const QqMusicFavoriteAlbumPageLoad({
    required this.offset,
    required this.nextOffset,
    required this.total,
    required this.hasMore,
    required this.omittedAlbumCount,
    required this.albums,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      nextOffset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      omittedAlbumCount.hashCode ^
      albums.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicFavoriteAlbumPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          nextOffset == other.nextOffset &&
          total == other.total &&
          hasMore == other.hasMore &&
          omittedAlbumCount == other.omittedAlbumCount &&
          albums == other.albums &&
          failure == other.failure;
}

enum QqMusicFavoriteAlbumPageLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}
