// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_playlist_summary`, `bridge_track_summary`, `domain_album_summary`, `domain_artist_summary`, `domain_playlist_id`, `domain_track_summary`, `failed_load`, `failed_track_page`, `map_error`, `map_load`, `map_track_page_error`, `map_track_page_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicUserPlaylistLoadHandle beginQqMusicUserPlaylistLoad() =>
    RustLib.instance.api.crateApiLibraryBeginQqMusicUserPlaylistLoad();

QqMusicPlaylistTrackPageLoadHandle beginQqMusicPlaylistTrackPageLoad({
  required String providerId,
  required String opaquePlaylistId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiLibraryBeginQqMusicPlaylistTrackPageLoad(
  providerId: providerId,
  opaquePlaylistId: opaquePlaylistId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicPlaylistTrackPageLoadHandle>>
abstract class QqMusicPlaylistTrackPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicPlaylistTrackPageLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicUserPlaylistLoadHandle>>
abstract class QqMusicUserPlaylistLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicUserPlaylistLoad> run();
}

class LibraryPlaylistSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? artworkUri;
  final int? trackCount;

  const LibraryPlaylistSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.artworkUri,
    this.trackCount,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artworkUri.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryPlaylistSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artworkUri == other.artworkUri &&
          trackCount == other.trackCount;
}

class LibraryTrackSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? subtitle;
  final List<String> artistNames;
  final List<CatalogArtistSummary> artists;
  final String? albumTitle;
  final CatalogAlbumSummary? album;
  final String? artworkUri;
  final int? durationSeconds;

  const LibraryTrackSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.subtitle,
    required this.artistNames,
    required this.artists,
    this.albumTitle,
    this.album,
    this.artworkUri,
    this.durationSeconds,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      artistNames.hashCode ^
      artists.hashCode ^
      albumTitle.hashCode ^
      album.hashCode ^
      artworkUri.hashCode ^
      durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryTrackSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          subtitle == other.subtitle &&
          artistNames == other.artistNames &&
          artists == other.artists &&
          albumTitle == other.albumTitle &&
          album == other.album &&
          artworkUri == other.artworkUri &&
          durationSeconds == other.durationSeconds;
}

class QqMusicPlaylistTrackPageLoad {
  final int offset;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicPlaylistTrackPageLoadFailure? failure;

  const QqMusicPlaylistTrackPageLoad({
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicPlaylistTrackPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicPlaylistTrackPageLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

class QqMusicUserPlaylistLoad {
  final List<LibraryPlaylistSummary> playlists;
  final QqMusicUserPlaylistLoadFailure? failure;

  const QqMusicUserPlaylistLoad({required this.playlists, this.failure});

  @override
  int get hashCode => playlists.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicUserPlaylistLoad &&
          runtimeType == other.runtimeType &&
          playlists == other.playlists &&
          failure == other.failure;
}

enum QqMusicUserPlaylistLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}
