// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicOwnedPlaylistLoadHandle beginQqMusicOwnedPlaylistLoad() =>
    RustLib.instance.api.crateApiLibraryBeginQqMusicOwnedPlaylistLoad();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicOwnedPlaylistLoadHandle>>
abstract class QqMusicOwnedPlaylistLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicOwnedPlaylistLoad> run();
}

class LibraryPlaylistSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? artworkUri;
  final int? trackCount;

  const LibraryPlaylistSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.artworkUri,
    this.trackCount,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artworkUri.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryPlaylistSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artworkUri == other.artworkUri &&
          trackCount == other.trackCount;
}

class QqMusicOwnedPlaylistLoad {
  final List<LibraryPlaylistSummary> playlists;
  final QqMusicOwnedPlaylistLoadFailure? failure;

  const QqMusicOwnedPlaylistLoad({required this.playlists, this.failure});

  @override
  int get hashCode => playlists.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicOwnedPlaylistLoad &&
          runtimeType == other.runtimeType &&
          playlists == other.playlists &&
          failure == other.failure;
}

enum QqMusicOwnedPlaylistLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}
