// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_playlist_summary`, `bridge_track_summary`, `domain_album_summary`, `domain_artist_summary`, `domain_playlist_id`, `domain_track_summary`, `failed_load`, `failed_track_page`, `map_error`, `map_load`, `map_track_page_error`, `map_track_page_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

UserPlaylistLoadHandle beginUserPlaylistLoad({required String providerId}) =>
    RustLib.instance.api.crateApiLibraryBeginUserPlaylistLoad(
      providerId: providerId,
    );

PlaylistTrackPageLoadHandle beginPlaylistTrackPageLoad({
  required String providerId,
  required String opaquePlaylistId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiLibraryBeginPlaylistTrackPageLoad(
  providerId: providerId,
  opaquePlaylistId: opaquePlaylistId,
  offset: offset,
  size: size,
);

RecentTrackPageLoadHandle beginRecentTrackPageLoad({
  required String providerId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiLibraryBeginRecentTrackPageLoad(
  providerId: providerId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaylistTrackPageLoadHandle>>
abstract class PlaylistTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<PlaylistTrackPageLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecentTrackPageLoadHandle>>
abstract class RecentTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<PlaylistTrackPageLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserPlaylistLoadHandle>>
abstract class UserPlaylistLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<UserPlaylistLoad> run();
}

enum LibraryPlaylistOwnership { unspecified, owned, saved }

class LibraryPlaylistSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? artworkUri;
  final int? trackCount;
  final bool isLikedSongs;
  final LibraryPlaylistOwnership? ownership;

  const LibraryPlaylistSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.artworkUri,
    this.trackCount,
    required this.isLikedSongs,
    this.ownership,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artworkUri.hashCode ^
      trackCount.hashCode ^
      isLikedSongs.hashCode ^
      ownership.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryPlaylistSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artworkUri == other.artworkUri &&
          trackCount == other.trackCount &&
          isLikedSongs == other.isLikedSongs &&
          ownership == other.ownership;
}

class LibraryTrackSummary {
  final String providerId;
  final String opaqueId;
  final String? membershipOpaqueId;
  final String title;
  final String? subtitle;
  final List<String> artistNames;
  final List<CatalogArtistSummary> artists;
  final String? albumTitle;
  final CatalogAlbumSummary? album;
  final String? artworkUri;
  final int? durationSeconds;

  const LibraryTrackSummary({
    required this.providerId,
    required this.opaqueId,
    this.membershipOpaqueId,
    required this.title,
    this.subtitle,
    required this.artistNames,
    required this.artists,
    this.albumTitle,
    this.album,
    this.artworkUri,
    this.durationSeconds,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      membershipOpaqueId.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      artistNames.hashCode ^
      artists.hashCode ^
      albumTitle.hashCode ^
      album.hashCode ^
      artworkUri.hashCode ^
      durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryTrackSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          membershipOpaqueId == other.membershipOpaqueId &&
          title == other.title &&
          subtitle == other.subtitle &&
          artistNames == other.artistNames &&
          artists == other.artists &&
          albumTitle == other.albumTitle &&
          album == other.album &&
          artworkUri == other.artworkUri &&
          durationSeconds == other.durationSeconds;
}

class PlaylistTrackPageLoad {
  final int offset;
  final int nextOffset;
  final int total;
  final bool totalIsExact;
  final bool hasMore;
  final int omittedTrackCount;
  final bool membershipIsExact;
  final List<String> membershipTrackOpaqueIds;
  final List<LibraryTrackSummary> tracks;
  final PlaylistTrackPageLoadFailure? failure;

  const PlaylistTrackPageLoad({
    required this.offset,
    required this.nextOffset,
    required this.total,
    required this.totalIsExact,
    required this.hasMore,
    required this.omittedTrackCount,
    required this.membershipIsExact,
    required this.membershipTrackOpaqueIds,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      nextOffset.hashCode ^
      total.hashCode ^
      totalIsExact.hashCode ^
      hasMore.hashCode ^
      omittedTrackCount.hashCode ^
      membershipIsExact.hashCode ^
      membershipTrackOpaqueIds.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistTrackPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          nextOffset == other.nextOffset &&
          total == other.total &&
          totalIsExact == other.totalIsExact &&
          hasMore == other.hasMore &&
          omittedTrackCount == other.omittedTrackCount &&
          membershipIsExact == other.membershipIsExact &&
          membershipTrackOpaqueIds == other.membershipTrackOpaqueIds &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum PlaylistTrackPageLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

class UserPlaylistLoad {
  final List<LibraryPlaylistSummary> playlists;
  final int omittedPlaylistCount;
  final UserPlaylistLoadFailure? failure;

  const UserPlaylistLoad({
    required this.playlists,
    required this.omittedPlaylistCount,
    this.failure,
  });

  @override
  int get hashCode =>
      playlists.hashCode ^ omittedPlaylistCount.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPlaylistLoad &&
          runtimeType == other.runtimeType &&
          playlists == other.playlists &&
          omittedPlaylistCount == other.omittedPlaylistCount &&
          failure == other.failure;
}

enum UserPlaylistLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}
