// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

RecentListeningHandle createRecentListening() =>
    RustLib.instance.api.crateApiListeningCreateRecentListening();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecentListeningHandle>>
abstract class RecentListeningHandle implements RustOpaqueInterface {
  LibraryTrackSummary? choose();

  void observe({
    LibraryTrackSummary? track,
    required int positionMs,
    required bool playing,
  });
}
