// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `await_load`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicLyricLoadHandle beginQqMusicLyricLoad({
  required String providerId,
  required String opaqueTrackId,
}) => RustLib.instance.api.crateApiLyricsBeginQqMusicLyricLoad(
  providerId: providerId,
  opaqueTrackId: opaqueTrackId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicLyricLoadHandle>>
abstract class QqMusicLyricLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicLyricLoad> run();
}

class QqMusicLyricLoad {
  final QqMusicSynchronizedLyrics? lyrics;
  final QqMusicLyricLoadFailure? failure;

  const QqMusicLyricLoad({this.lyrics, this.failure});

  @override
  int get hashCode => lyrics.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicLyricLoad &&
          runtimeType == other.runtimeType &&
          lyrics == other.lyrics &&
          failure == other.failure;
}

enum QqMusicLyricLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  unavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

class QqMusicSynchronizedLyricLine {
  final String text;
  final int startMs;
  final int durationMs;
  final List<QqMusicTimedLyricSegment> segments;
  final String? translation;
  final String? romanization;

  const QqMusicSynchronizedLyricLine({
    required this.text,
    required this.startMs,
    required this.durationMs,
    required this.segments,
    this.translation,
    this.romanization,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      startMs.hashCode ^
      durationMs.hashCode ^
      segments.hashCode ^
      translation.hashCode ^
      romanization.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicSynchronizedLyricLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startMs == other.startMs &&
          durationMs == other.durationMs &&
          segments == other.segments &&
          translation == other.translation &&
          romanization == other.romanization;
}

class QqMusicSynchronizedLyrics {
  final List<QqMusicSynchronizedLyricLine> lines;

  const QqMusicSynchronizedLyrics({required this.lines});

  @override
  int get hashCode => lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicSynchronizedLyrics &&
          runtimeType == other.runtimeType &&
          lines == other.lines;
}

class QqMusicTimedLyricSegment {
  final String text;
  final int startMs;
  final int durationMs;

  const QqMusicTimedLyricSegment({
    required this.text,
    required this.startMs,
    required this.durationMs,
  });

  @override
  int get hashCode => text.hashCode ^ startMs.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicTimedLyricSegment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startMs == other.startMs &&
          durationMs == other.durationMs;
}
