// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `await_resolution`, `domain_track_id`, `failed_resolution`, `map_error`, `map_resolution`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicMediaResolutionHandle beginQqMusicMediaResolution({
  required String providerId,
  required String opaqueTrackId,
}) => RustLib.instance.api.crateApiMediaBeginQqMusicMediaResolution(
  providerId: providerId,
  opaqueTrackId: opaqueTrackId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicMediaResolutionHandle>>
abstract class QqMusicMediaResolutionHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicMediaResolution> run();
}

enum QqMusicMediaFormat { mp3 }

enum QqMusicMediaQuality { standard }

class QqMusicMediaResolution {
  final QqMusicResolvedMediaSource? source;
  final QqMusicMediaResolutionFailure? failure;

  const QqMusicMediaResolution({this.source, this.failure});

  @override
  int get hashCode => source.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicMediaResolution &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          failure == other.failure;
}

enum QqMusicMediaResolutionFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  unavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

/// Short-lived playback input. The URI can contain authorization material and
/// is available to the playback edge, but never to Rust diagnostics.
class QqMusicResolvedMediaSource {
  final String uri;
  final QqMusicMediaFormat format;
  final QqMusicMediaQuality quality;
  final int validForSeconds;

  const QqMusicResolvedMediaSource({
    required this.uri,
    required this.format,
    required this.quality,
    required this.validForSeconds,
  });

  @override
  int get hashCode =>
      uri.hashCode ^
      format.hashCode ^
      quality.hashCode ^
      validForSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicResolvedMediaSource &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          format == other.format &&
          quality == other.quality &&
          validForSeconds == other.validForSeconds;
}
