// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `await_resolution`, `failed_resolution`, `map_error`, `map_resolution`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

MediaResolutionHandle beginMediaResolution({
  required String providerId,
  required String opaqueTrackId,
  required MediaQualityPreference preferredQuality,
}) => RustLib.instance.api.crateApiMediaBeginMediaResolution(
  providerId: providerId,
  opaqueTrackId: opaqueTrackId,
  preferredQuality: preferredQuality,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaResolutionHandle>>
abstract class MediaResolutionHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<MediaResolution> run();
}

enum MediaFormat { mp3 }

enum MediaQuality { standard, high }

enum MediaQualityPreference { standard, high }

class MediaResolution {
  final ResolvedMediaSource? source;
  final MediaResolutionFailure? failure;

  const MediaResolution({this.source, this.failure});

  @override
  int get hashCode => source.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaResolution &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          failure == other.failure;
}

enum MediaResolutionFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  unavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

/// Short-lived playback input. The URI can contain authorization material and
/// is available to the playback edge, but never to Rust diagnostics.
class ResolvedMediaSource {
  final String uri;
  final MediaFormat format;
  final MediaQuality quality;
  final int validForSeconds;

  const ResolvedMediaSource({
    required this.uri,
    required this.format,
    required this.quality,
    required this.validForSeconds,
  });

  @override
  int get hashCode =>
      uri.hashCode ^
      format.hashCode ^
      quality.hashCode ^
      validForSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedMediaSource &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          format == other.format &&
          quality == other.quality &&
          validForSeconds == other.validForSeconds;
}
