// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_video`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

TrackMusicVideoLoadHandle beginTrackMusicVideoLoad({
  required String providerId,
  required String opaqueTrackId,
}) => RustLib.instance.api.crateApiMusicVideoBeginTrackMusicVideoLoad(
  providerId: providerId,
  opaqueTrackId: opaqueTrackId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TrackMusicVideoLoadHandle>>
abstract class TrackMusicVideoLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<TrackMusicVideoLoad> run();
}

class TrackMusicVideoLoad {
  final TrackMusicVideoSummary? musicVideo;
  final TrackMusicVideoLoadFailure? failure;

  const TrackMusicVideoLoad({this.musicVideo, this.failure});

  @override
  int get hashCode => musicVideo.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMusicVideoLoad &&
          runtimeType == other.runtimeType &&
          musicVideo == other.musicVideo &&
          failure == other.failure;
}

enum TrackMusicVideoLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  sourceUnavailable,
  cancelled,
  alreadyRunning,
}

enum TrackMusicVideoQuality { fullHd, hd, sd, low }

class TrackMusicVideoSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final List<String> artistNames;
  final String? artworkUri;
  final int? durationSeconds;
  final String sourceUri;
  final TrackMusicVideoQuality quality;

  const TrackMusicVideoSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    required this.artistNames,
    this.artworkUri,
    this.durationSeconds,
    required this.sourceUri,
    required this.quality,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      artistNames.hashCode ^
      artworkUri.hashCode ^
      durationSeconds.hashCode ^
      sourceUri.hashCode ^
      quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMusicVideoSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          artistNames == other.artistNames &&
          artworkUri == other.artworkUri &&
          durationSeconds == other.durationSeconds &&
          sourceUri == other.sourceUri &&
          quality == other.quality;
}
