// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'authentication.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify_system_browser_cancellation`, `clear_attempt`, `failed_export`, `failed_restore`, `failed_sms`, `failed_start`, `failed_system_browser`, `failed_verification`, `lock_attempt`, `map_auth_error`, `map_progress`, `map_sms_error`, `map_system_browser_capture_failure`, `next_attempt`, `successful_sms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

int reserveNeteaseQrLoginStart() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseQrLoginStart();

Future<NeteaseQrLoginStart> startNeteaseQrLogin({required int attemptId}) =>
    RustLib.instance.api.crateApiNeteaseAuthenticationStartNeteaseQrLogin(
      attemptId: attemptId,
    );

bool cancelNeteaseQrLoginStart({required int attemptId}) =>
    RustLib.instance.api.crateApiNeteaseAuthenticationCancelNeteaseQrLoginStart(
      attemptId: attemptId,
    );

bool neteaseHasAuthenticatedCredential() => RustLib.instance.api
    .crateApiNeteaseAuthenticationNeteaseHasAuthenticatedCredential();

/// Whether a supported, root-owned Chromium-family binary is available on
/// Linux. This never starts the browser or inspects any browser profile.
bool neteaseSystemBrowserLoginSupported() => RustLib.instance.api
    .crateApiNeteaseAuthenticationNeteaseSystemBrowserLoginSupported();

/// Reserves a single serialized system-browser attempt. A newer reservation
/// replaces an older attempt, whose owner will close its browser and profile.
int reserveNeteaseSystemBrowserLogin() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseSystemBrowserLogin();

/// Runs the complete Linux official-browser path. Raw browser Cookie values
/// stay in Rust: they are staged, zeroed, and verified before this function
/// returns a coarse result to Dart.
Future<NeteaseSystemBrowserAuthenticationOutcome>
authenticateNeteaseWithSystemBrowser({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationAuthenticateNeteaseWithSystemBrowser(
      attemptId: attemptId,
    );

bool cancelNeteaseSystemBrowserLogin({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationCancelNeteaseSystemBrowserLogin(
      attemptId: attemptId,
    );

/// Cancels any attempt and waits until its browser/profile owner has completed
/// cleanup. Used by sign-out and provider replacement boundaries.
Future<bool> cancelActiveNeteaseSystemBrowserLoginAndWait() => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationCancelActiveNeteaseSystemBrowserLoginAndWait();

int reserveNeteaseSmsCodeRequest() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseSmsCodeRequest();

Future<NeteaseSmsAuthenticationOutcome> requestNeteaseSmsCode({
  required int attemptId,
  required String countryCode,
  required String phone,
}) => RustLib.instance.api.crateApiNeteaseAuthenticationRequestNeteaseSmsCode(
  attemptId: attemptId,
  countryCode: countryCode,
  phone: phone,
);

bool cancelNeteaseSmsCodeRequest({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationCancelNeteaseSmsCodeRequest(
      attemptId: attemptId,
    );

int? reserveNeteaseSmsLogin() =>
    RustLib.instance.api.crateApiNeteaseAuthenticationReserveNeteaseSmsLogin();

Future<NeteaseSmsAuthenticationOutcome> authenticateNeteaseSmsCode({
  required int attemptId,
  required String code,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationAuthenticateNeteaseSmsCode(
      attemptId: attemptId,
      code: code,
    );

bool cancelNeteaseSmsLogin({required int attemptId}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationCancelNeteaseSmsLogin(attemptId: attemptId);

/// Cancels the provider-owned phone-code session after a completed code
/// request. At that point no bridge attempt remains active, but the provider
/// still retains the short-lived challenge needed to authenticate the code.
bool cancelNeteaseSmsAuthentication() => RustLib.instance.api
    .crateApiNeteaseAuthenticationCancelNeteaseSmsAuthentication();

QqMusicCredentialExport exportNeteaseCredentialForSecureStorage() => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationExportNeteaseCredentialForSecureStorage();

QqMusicCredentialRestore restoreNeteaseCredentialFromSecureStorage({
  Uint8List? secretBytes,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationRestoreNeteaseCredentialFromSecureStorage(
      secretBytes: secretBytes,
    );

/// Stages the minimal Cookie header returned by an official `NetEase` web login.
/// The caller must run the normal credential verification before treating the
/// account as authenticated. Secret bytes are overwritten before returning.
QqMusicCredentialRestore stageNeteaseOfficialWebCredential({
  required List<int> secretBytes,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationStageNeteaseOfficialWebCredential(
      secretBytes: secretBytes,
    );

int? reserveNeteaseCredentialVerification() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseCredentialVerification();

Future<QqMusicCredentialVerification> verifyRestoredNeteaseCredential({
  required int attemptId,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationVerifyRestoredNeteaseCredential(
      attemptId: attemptId,
    );

bool cancelNeteaseCredentialVerification({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationCancelNeteaseCredentialVerification(
      attemptId: attemptId,
    );

bool signOutNetease() =>
    RustLib.instance.api.crateApiNeteaseAuthenticationSignOutNetease();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NeteaseQrLoginSessionHandle>>
abstract class NeteaseQrLoginSessionHandle implements RustOpaqueInterface {
  Future<QqMusicQrLoginUpdate> advance();

  bool cancel();

  bool get isActive;
}

class NeteaseQrLoginStart {
  final NeteaseQrLoginSessionHandle? session;
  final QqMusicQrChallenge? challenge;
  final String? externalConfirmationUrl;
  final QqMusicQrLoginFailure? failure;

  const NeteaseQrLoginStart({
    this.session,
    this.challenge,
    this.externalConfirmationUrl,
    this.failure,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      challenge.hashCode ^
      externalConfirmationUrl.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeteaseQrLoginStart &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          challenge == other.challenge &&
          externalConfirmationUrl == other.externalConfirmationUrl &&
          failure == other.failure;
}

enum NeteaseSmsAuthenticationFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  invalidInput,
  codeRejected,
  rateLimited,
  securityVerificationRequired,
  secondaryVerificationRequired,
  replaced,
  alreadyRunning,
}

class NeteaseSmsAuthenticationOutcome {
  final bool success;
  final NeteaseSmsAuthenticationFailure? failure;

  const NeteaseSmsAuthenticationOutcome({required this.success, this.failure});

  @override
  int get hashCode => success.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeteaseSmsAuthenticationOutcome &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          failure == other.failure;
}

enum NeteaseSystemBrowserAuthenticationFailure {
  unsupportedPlatform,
  browserUnavailable,
  browserLaunchFailed,
  profileSetupFailed,
  devtoolsUnavailable,
  devtoolsInvalid,
  officialTargetUnavailable,
  browserClosed,
  invalidCredential,
  timedOut,
  cancelled,
  cleanupFailed,
  rejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  coreUnavailable,
}

class NeteaseSystemBrowserAuthenticationOutcome {
  final bool authenticated;
  final NeteaseSystemBrowserAuthenticationFailure? failure;

  const NeteaseSystemBrowserAuthenticationOutcome({
    required this.authenticated,
    this.failure,
  });

  @override
  int get hashCode => authenticated.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeteaseSystemBrowserAuthenticationOutcome &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          failure == other.failure;
}
