// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'authentication.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_attempt`, `failed_export`, `failed_restore`, `failed_start`, `failed_verification`, `lock_attempt`, `map_auth_error`, `map_progress`, `next_attempt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

int reserveNeteaseQrLoginStart() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseQrLoginStart();

Future<NeteaseQrLoginStart> startNeteaseQrLogin({required int attemptId}) =>
    RustLib.instance.api.crateApiNeteaseAuthenticationStartNeteaseQrLogin(
      attemptId: attemptId,
    );

bool cancelNeteaseQrLoginStart({required int attemptId}) =>
    RustLib.instance.api.crateApiNeteaseAuthenticationCancelNeteaseQrLoginStart(
      attemptId: attemptId,
    );

bool neteaseHasAuthenticatedCredential() => RustLib.instance.api
    .crateApiNeteaseAuthenticationNeteaseHasAuthenticatedCredential();

QqMusicCredentialExport exportNeteaseCredentialForSecureStorage() => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationExportNeteaseCredentialForSecureStorage();

QqMusicCredentialRestore restoreNeteaseCredentialFromSecureStorage({
  Uint8List? secretBytes,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationRestoreNeteaseCredentialFromSecureStorage(
      secretBytes: secretBytes,
    );

int? reserveNeteaseCredentialVerification() => RustLib.instance.api
    .crateApiNeteaseAuthenticationReserveNeteaseCredentialVerification();

Future<QqMusicCredentialVerification> verifyRestoredNeteaseCredential({
  required int attemptId,
}) => RustLib.instance.api
    .crateApiNeteaseAuthenticationVerifyRestoredNeteaseCredential(
      attemptId: attemptId,
    );

bool cancelNeteaseCredentialVerification({required int attemptId}) => RustLib
    .instance
    .api
    .crateApiNeteaseAuthenticationCancelNeteaseCredentialVerification(
      attemptId: attemptId,
    );

bool signOutNetease() =>
    RustLib.instance.api.crateApiNeteaseAuthenticationSignOutNetease();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NeteaseQrLoginSessionHandle>>
abstract class NeteaseQrLoginSessionHandle implements RustOpaqueInterface {
  Future<QqMusicQrLoginUpdate> advance();

  bool cancel();

  bool get isActive;
}

class NeteaseQrLoginStart {
  final NeteaseQrLoginSessionHandle? session;
  final QqMusicQrChallenge? challenge;
  final QqMusicQrLoginFailure? failure;

  const NeteaseQrLoginStart({this.session, this.challenge, this.failure});

  @override
  int get hashCode => session.hashCode ^ challenge.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeteaseQrLoginStart &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          challenge == other.challenge &&
          failure == other.failure;
}
