// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_region`, `domain_region`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicNewAlbumPageLoadHandle beginQqMusicNewAlbumPageLoad({
  required QqMusicNewAlbumRegion region,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiNewAlbumsBeginQqMusicNewAlbumPageLoad(
  region: region,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicNewAlbumPageLoadHandle>>
abstract class QqMusicNewAlbumPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicNewAlbumPageLoad> run();
}

class CatalogNewAlbumRelease {
  final CatalogAlbumSummary album;
  final List<CatalogArtistSummary> artists;
  final String? releaseDate;

  const CatalogNewAlbumRelease({
    required this.album,
    required this.artists,
    this.releaseDate,
  });

  @override
  int get hashCode => album.hashCode ^ artists.hashCode ^ releaseDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogNewAlbumRelease &&
          runtimeType == other.runtimeType &&
          album == other.album &&
          artists == other.artists &&
          releaseDate == other.releaseDate;
}

class QqMusicNewAlbumPageLoad {
  final QqMusicNewAlbumRegion region;
  final int offset;
  final int total;
  final bool hasMore;
  final List<CatalogNewAlbumRelease> releases;
  final QqMusicNewAlbumPageLoadFailure? failure;

  const QqMusicNewAlbumPageLoad({
    required this.region,
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.releases,
    this.failure,
  });

  @override
  int get hashCode =>
      region.hashCode ^
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      releases.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicNewAlbumPageLoad &&
          runtimeType == other.runtimeType &&
          region == other.region &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          releases == other.releases &&
          failure == other.failure;
}

enum QqMusicNewAlbumPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}

enum QqMusicNewAlbumRegion {
  mainlandChina,
  hongKongTaiwan,
  western,
  korea,
  japan,
  other,
}
