// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_category`, `domain_category`, `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicNewSongsLoadHandle beginQqMusicNewSongsLoad({
  required QqMusicNewSongCategory category,
}) => RustLib.instance.api.crateApiNewSongsBeginQqMusicNewSongsLoad(
  category: category,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicNewSongsLoadHandle>>
abstract class QqMusicNewSongsLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicNewSongsLoad> run();
}

enum QqMusicNewSongCategory {
  mainlandChina,
  western,
  japan,
  korea,
  latest,
  hongKongTaiwan,
}

class QqMusicNewSongsLoad {
  final QqMusicNewSongCategory category;
  final List<LibraryTrackSummary> tracks;
  final QqMusicNewSongsLoadFailure? failure;

  const QqMusicNewSongsLoad({
    required this.category,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode => category.hashCode ^ tracks.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicNewSongsLoad &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicNewSongsLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
