// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_deletion`, `map_deletion`, `map_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

PlaylistDeletionHandle beginPlaylistDeletion({
  required String providerId,
  required String opaquePlaylistId,
}) => RustLib.instance.api.crateApiPlaylistDeletionBeginPlaylistDeletion(
  providerId: providerId,
  opaquePlaylistId: opaquePlaylistId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaylistDeletionHandle>>
abstract class PlaylistDeletionHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<PlaylistDeletionResult> run();
}

enum PlaylistDeletionFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  networkOutcomeUnknown,
  serviceUnavailable,
  invalidRequest,
  invalidResponseOutcomeUnknown,
  replacedOutcomeUnknown,

  /// Cancelling the local wait cannot recall a delete request already sent
  /// to the Provider, so presentation must refresh instead of assuming failure.
  cancelledOutcomeUnknown,
  alreadyRunning,
}

class PlaylistDeletionResult {
  final bool deleted;
  final PlaylistDeletionFailure? failure;

  const PlaylistDeletionResult({required this.deleted, this.failure});

  @override
  int get hashCode => deleted.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDeletionResult &&
          runtimeType == other.runtimeType &&
          deleted == other.deleted &&
          failure == other.failure;
}
