// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_creation`, `map_creation`, `map_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

QqMusicPlaylistCreationHandle beginQqMusicPlaylistCreation({
  required String name,
}) => RustLib.instance.api.crateApiPlaylistCreationBeginQqMusicPlaylistCreation(
  name: name,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicPlaylistCreationHandle>>
abstract class QqMusicPlaylistCreationHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicPlaylistCreationResult> run();
}

enum QqMusicPlaylistCreationFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  networkOutcomeUnknown,
  serviceUnavailable,
  invalidRequest,
  invalidResponseOutcomeUnknown,
  replacedOutcomeUnknown,

  /// Cancelling the local wait cannot recall a create request already sent
  /// to QQ Music, so presentation must refresh instead of assuming failure.
  cancelledOutcomeUnknown,
  alreadyRunning,
}

class QqMusicPlaylistCreationResult {
  final LibraryPlaylistSummary? createdPlaylist;
  final QqMusicPlaylistCreationFailure? failure;

  const QqMusicPlaylistCreationResult({this.createdPlaylist, this.failure});

  @override
  int get hashCode => createdPlaylist.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicPlaylistCreationResult &&
          runtimeType == other.runtimeType &&
          createdPlaylist == other.createdPlaylist &&
          failure == other.failure;
}
