// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_mutation`, `map_error`, `map_mutation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicPlaylistTrackMutationHandle beginQqMusicPlaylistTrackMutation({
  required String providerId,
  required String opaquePlaylistId,
  required String opaqueTrackId,
  required QqMusicPlaylistTrackState desiredState,
}) => RustLib.instance.api
    .crateApiPlaylistTracksBeginQqMusicPlaylistTrackMutation(
      providerId: providerId,
      opaquePlaylistId: opaquePlaylistId,
      opaqueTrackId: opaqueTrackId,
      desiredState: desiredState,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicPlaylistTrackMutationHandle>>
abstract class QqMusicPlaylistTrackMutationHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicPlaylistTrackMutationResult> run();
}

enum QqMusicPlaylistTrackMutationFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  networkOutcomeUnknown,
  serviceUnavailable,
  invalidRequest,
  invalidResponseOutcomeUnknown,
  replacedOutcomeUnknown,

  /// Cancelling the local wait cannot recall a write already sent to QQ
  /// Music, so presentation must refresh instead of assuming failure.
  cancelledOutcomeUnknown,
  alreadyRunning,
}

class QqMusicPlaylistTrackMutationResult {
  final QqMusicPlaylistTrackState? confirmedState;
  final QqMusicPlaylistTrackMutationFailure? failure;

  const QqMusicPlaylistTrackMutationResult({this.confirmedState, this.failure});

  @override
  int get hashCode => confirmedState.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicPlaylistTrackMutationResult &&
          runtimeType == other.runtimeType &&
          confirmedState == other.confirmedState &&
          failure == other.failure;
}

enum QqMusicPlaylistTrackState { present, absent }
