// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed`, `map_position_error`, `map_snapshot`, `with_queue`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

PlaybackQueueHandle createPlaybackQueue() =>
    RustLib.instance.api.crateApiQueueCreatePlaybackQueue();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaybackQueueHandle>>
abstract class PlaybackQueueHandle implements RustOpaqueInterface {
  PlaybackQueueUpdate advance();

  PlaybackQueueUpdate clear();

  PlaybackQueueUpdate completeCurrent();

  PlaybackQueueUpdate push({required LibraryTrackSummary track});

  PlaybackQueueUpdate remove({required int index});

  PlaybackQueueUpdate replace({
    required List<LibraryTrackSummary> tracks,
    int? currentIndex,
  });

  PlaybackQueueUpdate rewind();

  PlaybackQueueUpdate select({required int index});

  PlaybackQueueUpdate snapshot();
}

enum PlaybackQueueFailure { invalidTrack, invalidPosition, coreUnavailable }

class PlaybackQueueSnapshot {
  final List<LibraryTrackSummary> tracks;
  final int? currentIndex;
  final bool hasPrevious;
  final bool hasNext;

  const PlaybackQueueSnapshot({
    required this.tracks,
    this.currentIndex,
    required this.hasPrevious,
    required this.hasNext,
  });

  @override
  int get hashCode =>
      tracks.hashCode ^
      currentIndex.hashCode ^
      hasPrevious.hashCode ^
      hasNext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackQueueSnapshot &&
          runtimeType == other.runtimeType &&
          tracks == other.tracks &&
          currentIndex == other.currentIndex &&
          hasPrevious == other.hasPrevious &&
          hasNext == other.hasNext;
}

class PlaybackQueueUpdate {
  final PlaybackQueueSnapshot? snapshot;
  final bool currentChanged;
  final PlaybackQueueFailure? failure;

  const PlaybackQueueUpdate({
    this.snapshot,
    required this.currentChanged,
    this.failure,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^ currentChanged.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackQueueUpdate &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          currentChanged == other.currentChanged &&
          failure == other.failure;
}
