// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_ranking_summary`, `failed_group_load`, `failed_track_load`, `map_error`, `map_group_load`, `map_track_load`, `ranking_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicRankingGroupLoadHandle beginQqMusicRankingGroupLoad() =>
    RustLib.instance.api.crateApiRankingsBeginQqMusicRankingGroupLoad();

QqMusicRankingTrackPageLoadHandle beginQqMusicRankingTrackPageLoad({
  required String providerId,
  required String opaqueRankingId,
  required int offset,
  required int size,
}) => RustLib.instance.api.crateApiRankingsBeginQqMusicRankingTrackPageLoad(
  providerId: providerId,
  opaqueRankingId: opaqueRankingId,
  offset: offset,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicRankingGroupLoadHandle>>
abstract class QqMusicRankingGroupLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicRankingGroupLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicRankingTrackPageLoadHandle>>
abstract class QqMusicRankingTrackPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicRankingTrackPageLoad> run();
}

class CatalogRankingGroup {
  final String title;
  final List<CatalogRankingSummary> rankings;

  const CatalogRankingGroup({required this.title, required this.rankings});

  @override
  int get hashCode => title.hashCode ^ rankings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogRankingGroup &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          rankings == other.rankings;
}

class CatalogRankingSummary {
  final String providerId;
  final String opaqueId;
  final String title;
  final String? period;
  final String? artworkUri;
  final int? trackCount;

  const CatalogRankingSummary({
    required this.providerId,
    required this.opaqueId,
    required this.title,
    this.period,
    this.artworkUri,
    this.trackCount,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      opaqueId.hashCode ^
      title.hashCode ^
      period.hashCode ^
      artworkUri.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogRankingSummary &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          opaqueId == other.opaqueId &&
          title == other.title &&
          period == other.period &&
          artworkUri == other.artworkUri &&
          trackCount == other.trackCount;
}

class QqMusicRankingGroupLoad {
  final List<CatalogRankingGroup> groups;
  final QqMusicRankingLoadFailure? failure;

  const QqMusicRankingGroupLoad({required this.groups, this.failure});

  @override
  int get hashCode => groups.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicRankingGroupLoad &&
          runtimeType == other.runtimeType &&
          groups == other.groups &&
          failure == other.failure;
}

enum QqMusicRankingLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}

class QqMusicRankingTrackPageLoad {
  final CatalogRankingSummary? ranking;
  final int offset;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicRankingLoadFailure? failure;

  const QqMusicRankingTrackPageLoad({
    this.ranking,
    required this.offset,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      ranking.hashCode ^
      offset.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicRankingTrackPageLoad &&
          runtimeType == other.runtimeType &&
          ranking == other.ranking &&
          offset == other.offset &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}
