// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_load`, `failed_radar_load`, `map_error`, `map_load`, `map_radar_error`, `map_radar_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicRecommendedPlaylistPageLoadHandle
beginQqMusicRecommendedPlaylistPageLoad({
  required int offset,
  required int size,
}) => RustLib.instance.api
    .crateApiRecommendationsBeginQqMusicRecommendedPlaylistPageLoad(
      offset: offset,
      size: size,
    );

QqMusicRadarTrackPageLoadHandle beginQqMusicRadarTrackPageLoad({
  required int page,
}) => RustLib.instance.api
    .crateApiRecommendationsBeginQqMusicRadarTrackPageLoad(page: page);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicRadarTrackPageLoadHandle>>
abstract class QqMusicRadarTrackPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicRadarTrackPageLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicRecommendedPlaylistPageLoadHandle>>
abstract class QqMusicRecommendedPlaylistPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicRecommendedPlaylistPageLoad> run();
}

class QqMusicRadarTrackPageLoad {
  final int page;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicRadarTrackPageLoadFailure? failure;

  const QqMusicRadarTrackPageLoad({
    required this.page,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      page.hashCode ^ hasMore.hashCode ^ tracks.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicRadarTrackPageLoad &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicRadarTrackPageLoadFailure {
  coreUnavailable,
  authenticationRequired,
  credentialRejected,
  network,
  serviceUnavailable,
  invalidResponse,
  replaced,
  cancelled,
  alreadyRunning,
}

class QqMusicRecommendedPlaylistPageLoad {
  final int offset;
  final bool hasMore;
  final List<LibraryPlaylistSummary> playlists;
  final QqMusicRecommendedPlaylistPageLoadFailure? failure;

  const QqMusicRecommendedPlaylistPageLoad({
    required this.offset,
    required this.hasMore,
    required this.playlists,
    this.failure,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      hasMore.hashCode ^
      playlists.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicRecommendedPlaylistPageLoad &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          hasMore == other.hasMore &&
          playlists == other.playlists &&
          failure == other.failure;
}

enum QqMusicRecommendedPlaylistPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
