// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

QqMusicTrackSearchPageLoadHandle beginQqMusicTrackSearchPageLoad({
  required String query,
  required int page,
  required int size,
}) => RustLib.instance.api.crateApiSearchBeginQqMusicTrackSearchPageLoad(
  query: query,
  page: page,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicTrackSearchPageLoadHandle>>
abstract class QqMusicTrackSearchPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicTrackSearchPageLoad> run();
}

class QqMusicTrackSearchPageLoad {
  final int page;
  final int total;
  final bool hasMore;
  final List<LibraryTrackSummary> tracks;
  final QqMusicTrackSearchPageLoadFailure? failure;

  const QqMusicTrackSearchPageLoad({
    required this.page,
    required this.total,
    required this.hasMore,
    required this.tracks,
    this.failure,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      tracks.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicTrackSearchPageLoad &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          total == other.total &&
          hasMore == other.hasMore &&
          tracks == other.tracks &&
          failure == other.failure;
}

enum QqMusicTrackSearchPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
