// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'album.dart';
import 'artist.dart';
import 'library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_artist_load`, `failed_load`, `map_artist_error`, `map_artist_load`, `map_error`, `map_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

QqMusicTrackSearchPageLoadHandle beginQqMusicTrackSearchPageLoad({
  required String query,
  required int page,
  required int size,
}) => RustLib.instance.api.crateApiSearchBeginQqMusicTrackSearchPageLoad(
  query: query,
  page: page,
  size: size,
);

QqMusicArtistSearchPageLoadHandle beginQqMusicArtistSearchPageLoad({
  required String query,
  required int page,
  required int size,
}) => RustLib.instance.api.crateApiSearchBeginQqMusicArtistSearchPageLoad(
  query: query,
  page: page,
  size: size,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicArtistSearchPageLoadHandle>>
abstract class QqMusicArtistSearchPageLoadHandle
    implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicArtistSearchPageLoad> run();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QqMusicTrackSearchPageLoadHandle>>
abstract class QqMusicTrackSearchPageLoadHandle implements RustOpaqueInterface {
  bool cancel();

  bool get isActive;

  Future<QqMusicTrackSearchPageLoad> run();
}

class QqMusicArtistSearchPageLoad {
  final int page;
  final int total;
  final bool hasMore;
  final List<CatalogArtistSummary> artists;
  final QqMusicArtistSearchPageLoadFailure? failure;

  const QqMusicArtistSearchPageLoad({
    required this.page,
    required this.total,
    required this.hasMore,
    required this.artists,
    this.failure,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      artists.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicArtistSearchPageLoad &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          total == other.total &&
          hasMore == other.hasMore &&
          artists == other.artists &&
          failure == other.failure;
}

enum QqMusicArtistSearchPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}

class QqMusicTrackSearchItem {
  final LibraryTrackSummary track;
  final CatalogAlbumSummary? album;
  final List<CatalogArtistSummary> artists;

  const QqMusicTrackSearchItem({
    required this.track,
    this.album,
    required this.artists,
  });

  @override
  int get hashCode => track.hashCode ^ album.hashCode ^ artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicTrackSearchItem &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          album == other.album &&
          artists == other.artists;
}

class QqMusicTrackSearchPageLoad {
  final int page;
  final int total;
  final bool hasMore;
  final List<QqMusicTrackSearchItem> items;
  final QqMusicTrackSearchPageLoadFailure? failure;

  const QqMusicTrackSearchPageLoad({
    required this.page,
    required this.total,
    required this.hasMore,
    required this.items,
    this.failure,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      total.hashCode ^
      hasMore.hashCode ^
      items.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QqMusicTrackSearchPageLoad &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          total == other.total &&
          hasMore == other.hasMore &&
          items == other.items &&
          failure == other.failure;
}

enum QqMusicTrackSearchPageLoadFailure {
  coreUnavailable,
  network,
  serviceUnavailable,
  invalidResponse,
  cancelled,
  alreadyRunning,
}
