[package]
name = "rust_lib_flutterustmusic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0"
music-domain = { path = "../../crates/music-domain" }
provider-api = { path = "../../crates/provider-api" }
provider-qqmusic = { path = "../../crates/provider-qqmusic" }
qqmusic-client = { path = "../../crates/qqmusic-client" }
tokio = { version = "1.53.1", features = ["sync"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22.4"
rustls-platform-verifier = "0.7.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
unsafe_code = "allow"
